first_level_spells = {
    'absorb elements': {
        'description': 'The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type.',
        'level': '1st-level abjuration',
        'casting_time': '1 reaction, which you take when you take acid, cold, fire, lightning, or thunder damage',
        'range': 'Self',
        'components': 'S',
        'duration': '1 round',
        'school': 'Abjuration',

    },
    'alarm': {
        'description': 'You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won\'t set off the alarm. You also choose whether the alarm is mental or audible. \n\nA mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping.\n\nAn audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.',
        'level': '1st-level abjuration',
        'casting_time': '1 minute',
        'range': '30 feet',
        'components': 'V, S, M (a tiny bell and a piece of fine silver wire)',
        'duration': '8 hours',
        'school': 'Abjuration',
        'ritual': True,
    },
    'animal friendship': {
        'description': 'This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast\'s Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell\'s duration. If you or one of your companions harms the target, the spell ends.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a morsel of food)',
        'duration': '24 hours',
        'school': 'Enchantment',

    },
    'arcane weapon': {
        'description': 'You channel arcane energy into one simple or martial weapon you\'re holding, and choose one damage type: acid, cold, fire, lightning, poison, or thunder. Until the spell ends, you deal an extra 1d6 damage of the chosen type to any target you hit with the weapon. If the weapon isn\'t magical, it becomes a magic weapon for the spell\'s duration \n\nAs a bonus action, you can change the damage type, choosing from the options above\n\nWhen you cast this spell using a spell slot of 3rd level or higher, you can maintain your concentration on the spell for up to 8 hours.',
        'level': '1st-level transmutation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Transmutation',
        'concentration': True,

    },
    'armor of agathys': {
        'description': 'A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear. You gain 5 temporary hit points for the duration. If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, both the temporary hit points and the cold damage increase by 5 for each slot level above 1st.',
        'level': '1st-level abjuration',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (a cup of water)',
        'duration': '1 hour',
        'school': 'Abjuration',

    },
    'arms of hadar': {
        'description': 'You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and can\'t take reactions until its next turn. On a successful save, the creature takes half damage, but suffers no other effect.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': 'Self (10-foot radius)',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Conjuration',

    },
    'bane': {
        'description': 'Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a drop of blood)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'beast bond': {
        'description': 'You establish a telepathic link with one beast you touch that is friendly to you or charmed by you. The spell fails if the beast\'s Intelligence is 4 or higher. Until the spell ends, the link is active while you and the beast are within line of sight of each other. Through the link, the beast can understand your telepathic messages to it, and it can telepathically communicate simple emotions and concepts back to you. While the link is active, the beast gains advantage on Attack Rolls against any creature within 5 feet of you that you can see.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': '10 minutes',
        'school': 'Divination',

    },
    'bless': {
        'description': 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw. \n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a sprinkling of holy water)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'burning hands': {
        'description': 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one.\n\nThe fire ignites any flammable objects in the area that aren\'t being worn or carried.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': 'Self (15-foot cone)',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'catapult': {
        'description': 'Choose one object weighing 1 to 5 pounds within range that isn\'t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. When the object strikes something, the object and what it strikes each take 3d8 bludgeoning damage.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'S',
        'duration': 'Instantaneous',
        'school': 'Transmutation',

    },
    'cause fear': {
        'description': 'You awaken the sense of mortality in one creature you can see within range. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. \n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.',
        'level': '1st-level necromancy',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (a white feather or the heart of a hen)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Necromancy',
        'concentration': True,

    },
    'ceremony': {
        'description': 'You perform one of several religious ceremonies. When you cast the spell, choose one of the following ceremonies, the target of which must be within 10 feet of you throughout the casting.',
        'level': '1st-level abjuration',
        'casting_time': '1 hour',
        'range': 'Touch',
        'components': 'V, S, M (25 gp worth of powdered silver, which the spell consumes)',
        'duration': 'Instantaneous',
        'school': 'Abjuration',
        'ritual': True,

    },
    'chaos bolt': {
        'description': 'You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled on that die determines the attack\'s damage type, as shown below: ╔════╤═════════════╗\n║ d8 │ Damage Type ║\n╠════╪═════════════╣\n║ 1  │ Acid        ║\n╟────┼─────────────╢\n║ 2  │ Cold        ║\n╟────┼─────────────╢\n║ 3  │ Fire        ║\n╟────┼─────────────╢\n║ 4  │ Force       ║\n╟────┼─────────────╢\n║ 5  │ Lightning   ║\n╟────┼─────────────╢\n║ 6  │ Poison      ║\n╟────┼─────────────╢\n║ 7  │ Psychic     ║\n╟────┼─────────────╢\n║ 8  │ Thunder     ║\n╚════╧═════════════╝\n\n\nIf you roll the same number on both d8s, the chaotic energy leaps from the target to a different creature of your choice within 30 feet of it. Make a new Attack Roll against the new target, and make a new Damage Roll, which could cause the chaotic energy to leap again.\n\nA creature can be targeted only once by each casting of this spell.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage of the type rolled for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'charm person': {
        'description': 'You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and it does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you. \n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S',
        'duration': '1 hour',
        'school': 'Enchantment',

    },
    'chromatic orb': {
        'description': 'You hurl a 4-inch-diameter sphere of energy at a creature that you can see within range. You choose acid, cold, fire, lightning, poison, or thunder for the type of orb you create, and then make a ranged spell attack against the target. If the attack hits, the creature takes 3d8 damage of the type you chose.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '90 feet',
        'components': 'V, S, M (a diamond worth at least 50 gp)',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'color spray': {
        'description': 'A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can\'t see).\n\nStarting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the end of your next turn. Subtract each creature\'s hit points from the total before moving on to the creature with the next lowest hit points. A creature\'s hit points must be equal to or less than the remaining total for that creature to be affected.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d10 for each slot level above 1st.',
        'level': '1st-level illusion',
        'casting_time': '1 action',
        'range': 'Self (15-foot cone)',
        'components': 'V, S, M (a pinch of powder or sand that is colored red, yellow, and blue)',
        'duration': '1 round',
        'school': 'Illusion',

    },
    'command': {
        'description': 'You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn\'t understand your language, or if your command is directly harmful to it. \n\nSome typical commands and their effects follow. You might issue a command other than one described here. If you do so, the DM determines how the target behaves. If the target can\'t follow your command, the spell ends.\n\n*Approach* \nThe target moves toward you by the shortest and most direct route, ending its turn if it moves within 5 feet of you.\n\n*Drop*\nThe target drops whatever it is holding and then ends its turn.\n\n*Flee*\nThe target spends its turn moving away from you by the fastest available means.\n\nGrovel\nThe target falls prone and then ends its turn.\n\n*Halt*\nThe target doesn\'t move and takes no actions. A flying creature stays aloft, provided that it is able to do so. If it must move to stay aloft, it flies the minimum distance needed to remain in the air.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can affect one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V',
        'duration': '1 round',
        'school': 'Enchantment',

    },
    'compelled duel': {
        'description': 'You attempt to compel a creature into a duel. One creature that you can see within range must make a Wisdom saving throw. On a failed save, the creature is drawn to you, compelled by your divine demand. For the duration, it has disadvantage on attack rolls against creatures other than you, and must make a Wisdom saving throw each time it attempts to move to a space that is more than 30 feet away from you; if it succeeds on this saving throw, this spell doesn\'t restrict the target\'s movement for that turn.\n\nThe spell ends if you attack any other creature, if you cast a spell that targets a hostile creature other than the target, if a creature friendly to you damages the target or casts a harmful spell on it, or if you end your turn more than 30 feet away from the target.',
        'level': '1st-level enchantment',
        'casting_time': '1 bonus action',
        'range': '30 feet',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'comprehend languages': {
        'description': 'For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text.\n\nThis spell doesn\'t decode secret messages in a text or a glyph, such as an arcane sigil, that isn\'t part of a written language.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (a pinch of soot and salt)',
        'duration': '1 hour',
        'school': 'Divination',
        'ritual': True,
    },
    'create or destroy water': {
        'description': 'You either create or destroy water.\n\n*Create Water*\nYou create up to 10 gallons of clean water within range in an open container. Alternatively, the water falls as rain in a 30-foot cube within range, extinguishing exposed flames in the area.\n\n*Destroy Water*\nYou destroy up to 10 gallons of water in an open container within range. Alternatively, you destroy fog in a 30-foot cube within range.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you create or destroy 10 additional gallons of water, or the size of the cube increases by 5 feet, for each slot level above 1st.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a drop of water if creating water or a few grains of sand if destroying it)',
        'duration': 'Instantaneous',
        'school': 'Transmutation',

    },
    'cure wounds': {
        'description': 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'detect evil and good': {
        'description': 'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located. Similarly, you know if there is a place or object within 30 feet of you that has been magically consecrated or desecrated.\n\n The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Divination',
        'concentration': True,

    },
    'detect magic': {
        'description': 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.\n\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Divination',
        'concentration': True,

    },
    'detect poison and disease': {
        'description': 'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease in each case. \n\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (a yew leaf)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Divination',
        'concentration': True,

    },
    'disguise self': {
        'description': 'You make yourself--including your clothing, armor, weapons, and other belongings on your person--look different until the spell ends or until you use your action to dismiss it. You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can\'t change your body type, so you must adopt a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you.\n\nThe changes wrought by this spell fail to hold up to physical inspection. For example, if you use this spell to add a hat to your outfit, objects pass through the hat, and anyone who touches it would feel nothing or would feel your head and hair. If you use this spell to appear thinner than you are, the hand of someone who reaches out to touch you would bump into you while it was seemingly still in midair.\n\nTo discern that you are disguised, a creature can use its action to inspect your appearance and must succeed on an Intelligence (Investigation) check against your Spell Save DC.',
        'level': '1st-level illusion',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': '1 hour',
        'school': 'Illusion',

    },
    'dissonant whispers': {
        'description': 'You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. The creature doesn\'t move into obviously dangerous ground, such as a fire or a pit. On a successful save, the target takes half as much damage and doesn\'t have to move away. A deafened creature automatically succeeds on the save.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V',
        'duration': 'Instantaneous',
        'school': 'Enchantment',

    },
    'distort value': {
        'description': 'You cast this spell on an object no more than 1 foot on a side, doubling the object\'s perceived value by adding illusionary flourish or reducing its perceived value by half with the help of illusionary dents and scratches. Anyone examining the object must roll an Investigation check against your spell DC.\n\nWhen you cast this spell using a higher spell slot, you increase the size of the object by 1 foot per spell slot over 1st.',
        'level': '1st-level illusion',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Illusion',
        'concentration': True,

    },
    'divine favor': {
        'description': 'Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.',
        'level': '1st-level evocation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'earth tremor': {
        'description': 'You cause a tremor in the ground within range. Each creature other than you in that area must make a Dexterity saving throw. On a failed save, a creature takes 1d6 bludgeoning damage and is knocked prone. If the ground in that area is loose earth or stone, it becomes difficult terrain until cleared, with each 5-foot-diameter portion requiring at least 1 minute to clear by hand.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': 'Self (10-foot radius)',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'ensnaring strike': {
        'description': 'The next time you hit a creature with a weapon attack before this spell ends, a writhing mass of thorny vines appears at the point of impact, and the target must succeed on a Strength saving throw or be restrained by the magical vines until the spell ends. A Large or larger creature has advantage on the saving throw. If the target succeeds on the save, the vines shrivel away.\n\nWhile restrained by this spell, the target takes 1d6 piercing damage at the start of each of its turns. A creature restrained by the vines or one that can touch the creature can use its action to make a Strength Check against your Spell Save DC. On a success, the target is freed.\n\nIf you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level conjuration',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Conjuration',
        'concentration': True,

    },
    'entangle': {
        'description': 'Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. \n\nA creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A creature restrained by the plants can use its action to make a Strength check against your spell save DC. On a success, it frees itself.\n\nWhen the spell ends, the conjured plants wilt away.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '90 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Conjuration',
        'concentration': True,

    },
    'expeditious retreat': {
        'description': 'This spell allows you to move at an incredible pace. When you cast this spell, and then as a bonus action on each of your turns until the spell ends, you can take the Dash action.',
        'level': '1st-level transmutation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Transmutation',
        'concentration': True,

    },
    'faerie fire': {
        'description': 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. \n\nAny attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can\'t benefit from being invisible.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'false life': {
        'description': 'Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you gain 5 additional temporary hit points for each slot level above 1st.',
        'level': '1st-level necromancy',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (a small amount of alcohol or distilled spirits)',
        'duration': '1 hour',
        'school': 'Necromancy',
        
    },
    'feather fall': {
        'description': 'Choose up to five falling creatures within range. A falling creature\'s rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature.',
        'level': '1st-level transmutation',
        'casting_time': '1 reaction, which you take when you or a creature within 60 feet of you falls',
        'range': '60 feet',
        'components': 'V, M (a small feather or piece of down)',
        'duration': '1 minute',
        'school': 'Transmutation',

    },
    'find familiar': {
        'description': 'You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast.\n\nAdditional animal form choices may be available at the DM\'s discretion.\n\nYour familiar acts independently of you, but it always obeys your commands. In combat, it rolls its own initiative and acts on its own turn. A familiar can\'t attack, but it can take other actions as normal.\n\nWhen the familiar drops to 0 hit points, it disappears, leaving behind no physical form. It reappears after you cast this spell again.\n\nWhile your familiar is within 100 feet of you, you can communicate with it telepathically. Additionally, as an action, you can see through your familiar\'s eyes and hear what it hears until the start of your next turn, gaining the benefits of any special senses that the familiar has. During this time, you are deaf and blind with regard to your own senses.\n\nAs an action, you can temporarily dismiss your familiar. It disappears into a pocket dimension where it awaits your summons. Alternatively, you can dismiss it forever. As an action while it is temporarily dismissed, you can cause it to reappear in any unoccupied space within 30 feet of you.\n\nYou can\'t have more than one familiar at a time. If you cast this spell while you already have a familiar, you instead cause it to adopt a new form. Choose one of the forms from the above list. Your familiar transforms into the chosen creature.\n\nFinally, when you cast a spell with a range of touch, your familiar can deliver the spell as if it had cast the spell. Your familiar must be within 100 feet of you, and it must use its reaction to deliver the spell when you cast it. If the spell requires an Attack Roll, you use your Attack Modifier for the roll.',
        'level': '1st-level conjuration (ritual)',
        'casting_time': '1 hour',
        'range': '10 feet',
        'components': 'V, S, M (10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier)',
        'duration': 'Instantaneous',
        'school': 'Conjuration',
        'ritual': True
    },
    'fog cloud': {
        'description': 'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the radius of the fog increases by 20 feet for each slot level above 1st.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Conjuration',
        'concentration': True,

    },
    'goodberry': {
        'description': 'Up to ten berries appear in your hand and are infused with magic for the duration. A creature can use its action to eat one berry. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day.\n\nThe berries lose their potency if they have not been consumed within 24 hours of the casting of this spell.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (a sprig of mistletoe)',
        'duration': 'Instantaneous',
        'school': 'Transmutation',

    },
    'grease': {
        'description': 'Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into difficult terrain for the duration. \n\nWhen the grease appears, each creature standing in its area must succeed on a Dexterity saving throw or fall prone. A creature that enters the area or ends its turn there must also succeed on a Dexterity saving throw or fall prone.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (a bit of pork rind or butter)',
        'duration': '1 minute',
        'school': 'Conjuration',

    },
    'guiding bolt': {
        'description': 'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': '1 round',
        'school': 'Evocation',

    },
    'hail of thorns': {
        'description': 'The next time you hit a creature with a ranged weapon attack before the spell ends, this spell creates a rain of thorns that sprouts from your ranged weapon or ammunition. In addition to the normal effect of the attack, the target of the attack and each creature within 5 feet of it must make a Dexterity saving throw. A creature takes 1d10 piercing damage on a failed save, or half as much damage on a successful one.\n\nIf you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st (to a maximum of 6d10).',
        'level': '1st-level conjuration',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Conjuration',
        'concentration': True,

    },
    'healing word': {
        'description': 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 bonus action',
        'range': '60 feet',
        'components': 'V',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'hellish rebuke': {
        'description': 'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames. The creature must make a Dexterity saving throw. It takes 2d10 fire damage on a failed save, or half as much damage on a successful one.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 reaction, which you take in response to being damaged by a creature within 60 feet of you that you can see',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'heroism': {
        'description': 'A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier at the start of each of its turns. When the spell ends, the target loses any remaining temporary hit points from this spell.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'hex': {
        'description': 'Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability.\n\nIf the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to curse a new creature.\n\nA remove curse cast on the target ends this spell early.\n\nWhen you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.',
        'level': '1st-level enchantment',
        'casting_time': '1 bonus action',
        'range': '90 feet',
        'components': 'V, S, M (the petrified eye of a newt)',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Enchantment',
        'concentration': True,

    },
    "hunter's mark": {
        'description': "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.\n\nWhen you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.",
        'level': '1st-level divination',
        'casting_time': '1 bonus action',
        'range': '90 feet',
        'components': 'V',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Divination',
        'concentration': True,

    },
    'ice knife': {
        'description': 'You create a shard of ice and fling it at one creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 piercing damage. Hit or miss, the shard then explodes. The target and each creature within 5 feet of it must succeed on a Dexterity saving throw or take 2d6 cold damage.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the cold damage increases by 1d6 for each slot level above 1st.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'S, M (a drop of water or piece of ice)',
        'duration': 'Instantaneous',
        'school': 'Conjuration',

    },
    'identify': {
        'description': 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any. You learn whether any spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.\n\nIf you instead touch a creature throughout the casting, you learn what spells, if any, are currently affecting it.',
        'level': '1st-level divination',
        'casting_time': '1 minute',
        'range': 'Touch',
        'components': 'V, S, M (a pearl worth at least 100 gp and an owl feather)',
        'duration': 'Instantaneous',
        'school': 'Divination',
        'ritual': True

    },
    'illusory script': {
        'description': 'You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration. \n\nTo you and any creatures you designate when you cast the spell, the writing appears normal, written in your hand, and conveys whatever meaning you intended when you wrote the text. To all others, the writing appears as if it were written in an unknown or magical script that is unintelligible. Alternatively, you can cause the writing to appear to be an entirely different message, written in a different hand and language, though the language must be one you know.\n\nShould the spell be dispelled, the original script and the illusion both disappear.\n\nA creature with truesight can read the hidden message.',
        'level': '1st-level illusion',
        'casting_time': '1 minute',
        'range': 'Touch',
        'components': 'S, M (a lead-based ink worth at least 10 gp, which the spell consumes)',
        'duration': '10 days',
        'school': 'Illusion',
        'ritual': True

    },
    'inflict wounds': {
        'description': 'Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.',
        'level': '1st-level necromancy',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Necromancy',

    },
    'jump': {
        'description': 'You touch a creature. The creature\'s jump distance is tripled until the spell ends.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (a grasshopper\'s hind leg)',
        'duration': '1 minute',
        'school': 'Transmutation',
        'concentration': True,

    },
    'longstrider': {
        'description': 'You touch a creature. The target\'s speed increases by 10 feet until the spell ends.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (a pinch of dirt)',
        'duration': '1 hour',
        'school': 'Transmutation',
        'concentration': True,

    },
    'mage armor': {
        'description': 'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
        'level': '1st-level abjuration',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (a piece of cured leather)',
        'duration': '8 hours',
        'school': 'Abjuration',

    },
    'magic missile': {
        'description': 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'protection from evil and good': {
        'description': 'Until the spell ends, one willing creature you touch is protected against certain types of creatures: aberrations, celestials, elementals, fey, fiends, and undead.\n\nThe protection grants several benefits. Creatures of those types have disadvantage on attack rolls against the target. The target also can\'t be charmed, frightened, or possessed by them. If the target is already charmed, frightened, or possessed by such a creature, the target has advantage on any new saving throw against the relevant effect.',
        'level': '1st-level abjuration',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (holy water or powdered silver and iron, which the spell consumes)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Abjuration',
        'concentration': True,

    },
    'purify food and drink': {
        'description': 'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.',
        'level': '1st-level transmutation',
        'casting_time': '1 action',
        'range': '10 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Transmutation',

    },
    'ray of sickness': {
        'description': 'Make a ranged spell attack against a creature you can see within range. On a hit, the target takes 2d8 poison damage and must make a Constitution saving throw. On a failed save, it is also poisoned until the end of your next turn.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
        'level': '1st-level necromancy',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Necromancy',

    },
    'sanctuary': {
        'description': 'You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn\'t protect the warded creature from area effects, such as the explosion of a fireball.\n\nIf the warded creature makes an attack, casts a spell that affects an enemy, or deals damage to another creature, this spell ends.',
        'level': '1st-level abjuration',
        'casting_time': '1 bonus action',
        'range': '30 feet',
        'components': 'V, S, M (a small silver mirror)',
        'duration': '1 minute',
        'school': 'Abjuration',

    },
    'searing smite': {
        'description': 'The next time you hit a creature with a melee weapon attack during this spell\'s duration, your weapon flares with white-hot intensity, and the attack deals an extra 1d6 fire damage to the target and causes the target to ignite in flames. At the start of each of its turns until the spell ends, the target must make a Constitution saving throw. On a failed save, it takes 1d6 fire damage. On a successful save, the spell ends. If the target or a creature within 5 feet of it uses an action to put out the flames, or if some other effect douses the flames (such as the target being submerged in water), the spell ends.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the initial extra damage dealt by the attack increases by 1d6 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'shield of faith': {
        'description': 'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.',
        'level': '1st-level abjuration',
        'casting_time': 'Bonus Action',
        'range': '60 ft',
        'components': 'V, S, M',
        'duration': '10 Minutes',
        'school': 'Abjuration',
        'concentration': True,

    },
    'shield': {
        'description': 'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
        'level': '1st-level abjuration',
        'casting_time': '1 reaction',
        'range': 'Self',
        'components': 'V, S',
        'duration': '1 round',
        'school': 'Abjuration',

    },
    'silent image': {
        'description': 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube. The image appears at a spot within range and lasts for the duration. The image is purely visual; it isn\'t accompanied by sound, smell, or other sensory effects.\n\nYou can use your action to cause the image to move to any spot within range. As the image changes location, you can alter its appearance so that its movements appear natural for the image. For example, if you create an image of a creature and move it, you can alter the image so that it appears to be walking.\n\nPhysical interaction with the image reveals it to be an illusion, because things can pass through it. A creature that uses its action to examine the image can determine that it is an illusion with a successful Intelligence (Investigation) check against your Spell Save DC. If a creature discerns the illusion for what it is, the creature can see through the image.',
        'level': '1st-level illusion',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (a bit of fleece)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Illusion',
        'concentration': True,

    },
    'snare': {
        'description': 'As you cast this spell, you use the rope to create a circle with a 5-foot radius on the ground or the floor. When you finish casting, the rope disappears and the circle becomes a magic trap.\n\nThis trap is nearly invisible, requiring a successful Intelligence (Investigation) check against your Spell Save DC to be discerned.\n\nThe trap triggers when a small, medium, or large creature moves onto the ground or the floor in the spell\'s radius. That creature must succeed on a Dexterity Saving Throw or be magically hoisted into the air, leaving it hanging upside down 3 feet above the ground or the floor. The creature is restrained there until the spell ends.\n\nA restrained creature can make a Dexterity Saving Throw at the end of each of its turns, ending the effect on itself on a success. Alternatively, the creature or someone else who can reach it can use an action to make an Intelligence (Arcana) check against your Spell Save DC. On a success, the restrained effect ends.\n\nAfter the trap is triggered, the spell ends when no creature is restrained by it.',
        'level': '1st-level abjuration',
        'casting_time': '1 minute',
        'range': 'Touch',
        'components': 'V, S, M (25 feet of rope, which the spell consumes)',
        'duration': '8 hours',
        'school': 'Abjuration',

    },
    'sleep': {
        'description': 'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures).\n\n Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature\'s hit points from the total before moving on to the creature with the next lowest hit points. A creature\'s hit points must be equal to or less than the remaining total for that creature to be affected.\n\nUndead and creatures immune to being charmed aren\'t affected by this spell.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '90 feet',
        'components': 'V, S, M (a pinch of fine sand, rose petals, or a cricket)',
        'duration': '1 minute',
        'school': 'Enchantment',

    },
    'speak with animals': {
        'description': 'You gain the ability to comprehend and verbally communicate with beasts for the duration. The knowledge and awareness of many beasts is limited by their intelligence, but at minimum, beasts can give you information about nearby locations and monsters, including whatever they can perceive or have perceived within the past day. You might be able to persuade a beast to perform a small favor for you, at the DM\'s discretion.',
        'level': '1st-level divination',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': '10 minutes',
        'school': 'Divination',
        'concentration': True,

    },
    'tashas hideous laughter': {
        'description': 'A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a Wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn\'t affected.\n\nAt the end of each of its turns, and each time it takes damage, the target can make another Wisdom Saving Throw. The target has advantage on the Saving Throw if it\'s triggered by damage. On a success, the spell ends.',
        'level': '1st-level enchantment',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (tiny tarts and a feather that is waved in the air)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'tensers floating disk': {
        'description': 'This spell creates a circular, horizontal plane of force, 3 feet in diameter and 1 inch thick, that floats 3 feet above the ground in an unoccupied space of your choice that you can see within range. The disk remains for the duration and can hold up to 500 pounds. If more weight is placed on it, the spell ends, and everything on the disk falls to the ground.\n\nThe disk is immobile while you are within 20 feet of it. If you move more than 20 feet away from it, the disk follows you so that it remains within 20 feet of you. It can move across uneven terrain, up or down stairs, slopes and the like, but it can\'t cross an elevation change of 10 feet or more. For example, the disk can\'t move across a 10-foot-deep pit, nor could it leave such a pit if it was created at the bottom.\n\nIf you move more than 100 feet from the disk (typically because it can\'t move around an obstacle to follow you), the spell ends.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a drop of mercury)',
        'duration': '1 hour',
        'school': 'Conjuration',
        'ritual': True

    },
    'thunderous smite': {
        'description': 'The first time you hit with a melee weapon attack during this spell\'s duration, your weapon rings with thunder that is audible within 300 feet of you, and the attack deals an extra 2d6 thunder damage to the target. Additionally, if the target is a creature, it must succeed on a Strength saving throw or be pushed 10 feet away from you and knocked prone.',
        'level': '1st-level evocation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'thunderwave': {
        'description': 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.\n\nIn addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you by the spell\'s effect, and the spell emits a thunderous boom audible out to 300 feet.\n\nWhen you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': 'Self (15-foot cube)',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',

    },
    'unseen servant': {
        'description': 'This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 hit point, and a Strength of 2, and it can\'t attack. If it drops to 0 hit points, the spell ends. \n\nOnce on each of your turns as a bonus action, you can mentally command the servant to move up to 15 feet and interact with an object. The servant can perform simple tasks that a human servant could do, such as fetching things, cleaning, mending, folding clothes, lighting fires, serving food, and pouring wine. Once you give the command, the servant performs the task to the best of its ability until it completes the task, then waits for your next command.\n\nIf you command the servant to perform a task that would move it more than 60 feet away from you, the spell ends.',
        'level': '1st-level conjuration',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (a piece of string and a bit of wood)',
        'duration': '1 hour',
        'school': 'Conjuration',
        'ritual': True

    },
    'witch bolt': {
        'description': 'A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against that creature. On a hit, the target takes 1d12 lightning damage, and on each of your turns for the duration, you can use your action to deal 1d12 lightning damage to the target automatically. The spell ends if you use your action to do anything else. The spell also ends if the target is ever outside the spell\'s range or if it has total cover from you.',
        'level': '1st-level evocation',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a twig from a tree that has been struck by lightning)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'wrathful smite': {
        'description': 'The next time you hit with a melee weapon attack during this spell\'s duration, your attack deals an extra 1d6 psychic damage. Additionally, if the target is a creature, it must make a Wisdom saving throw or be frightened of you until the spell ends. As an action, the creature can make a Wisdom check against your spell save DC to steel its resolve and end this spell.',
        'level': '1st-level evocation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'zephyr strike': {
        'description': 'You move like the wind. Until the spell ends, your movement doesn\'t provoke opportunity attacks.\n\nOnce before the spell ends, you can give yourself advantage on one Weapon Attack Roll on your turn. That attack deals an extra 1d8 force damage on a hit. Whether you hit or miss, your walking speed increases by 30 feet until the end of that turn.',
        'level': '1st-level transmutation',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Transmutation',
        'concentration': True,

    }
}
