fifth_level_spells = {
    'animate object': {
        'description': 'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, large targets count as four objects, huge targets count as eight objects. You can\'t animate any object larger than huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points.\n\nAs a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.\n╔══════════════════════════╤════╤════╤════════════════════════════╤══════════╤══════════╗\n║ Size                     │ HP │ AC │ Attack                     │ Str      │ Dex      ║\n╠══════════════════════════╪════╪════╪════════════════════════════╪══════════╪══════════╣\n║ Animated Object (Tiny)   │ 20 │ 18 │ +8 to hit, 1d4 + 4 damage  │ 1d20 - 3 │ 1d20 + 4 ║\n╟──────────────────────────┼────┼────┼────────────────────────────┼──────────┼──────────╢\n║ Animated Object (Small)  │ 25 │ 16 │ +6 to hit, 1d8 + 2 damage  │ 1d20 - 2 │ 1d20 + 2 ║\n╟──────────────────────────┼────┼────┼────────────────────────────┼──────────┼──────────╢\n║ Animated Object (Medium) │ 40 │ 13 │ +5 to hit, 2d6 + 1 damage  │ 1d20     │ 1d20 + 1 ║\n╟──────────────────────────┼────┼────┼────────────────────────────┼──────────┼──────────╢\n║ Animated Object (Large)  │ 50 │ 10 │ +6 to hit, 2d10 + 2 damage │ 1d20 + 2 │ 1d20     ║\n╟──────────────────────────┼────┼────┼────────────────────────────┼──────────┼──────────╢\n║ Animated Object (Huge)   │ 80 │ 10 │ +8 to hit, 2d12 + 4 damage │ 1d20 + 4 │ 1d20 - 3 ║\n╚══════════════════════════╧════╧════╧════════════════════════════╧══════════╧══════════╝\nAn animated object is a construct with AC, hit points, attacks, Strength, and Dexterity determined by its size. Its Constitution is 10 and its Intelligence and Wisdom are 3, and its Charisma is 1. Its speed is 30 feet; if the object lacks legs or other appendages it can use for locomotion, it instead has a flying speed of 30 feet and can hover. If the object is securely attached to a surface or a larger object, such as a chain bolted to a wall, its speed is 0. It has blindsight with a radius of 30 feet and is blind beyond that distance. When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form.\n\nIf you command an object to attack, it can make a single Melee Attack against a creature within 5 feet of it. It makes a slam attack with an attack bonus and bludgeoning damage determined by its size. The DM might rule that a specific object inflicts slashing or piercing damage based on its form.\n\nIf you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': '1 minute',
        'school': 'Transmutation',
        'concentration': False,

    },
    'antilife shell': {
        'description': 'A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration.\n\nThe barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier.\n\nIf you move so that an affected creature is forced to pass through the barrier, the spell ends.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (a small piece of shell)',
        'duration': '1 hour',
        'school': 'Abjuration',
        'concentration': False,

    },
    'awaken': {
        'description': 'After spending the casting time tracing magical pathways within a precious gemstone, you touch a huge or smaller beast or plant. The target must have either no Intelligence Score or an Intelligence of 3 or less. The target gains an Intelligence of 10. The target also gains the ability to speak one language you know. If the target is a plant, it gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a Human\'s. Your DM chooses statistics appropriate for the awakened plant, such as the statistics for the Awakened Shrub or the Awakened Tree.\n\nThe awakened beast or plant is charmed by you for 30 days or until you or your companions do anything harmful to it. When the charmed condition ends, the awakened creature chooses whether to remain friendly to you, based on how you treated it while it was charmed.',
        'level': '5',
        'casting_time': '8 hours',
        'range': 'Touch',
        'components': 'V, S, M (an agate worth at least 1,000 gp, which the spell consumes)',
        'duration': 'Instantaneous',
        'school': 'Transmutation',
        'concentration': False,

    },
    'banishing smite': {
        'description': 'The next time you hit a creature with a Weapon Attack before this spell ends, your weapon crackles with force, and the attack deals an extra 5d10 force damage to the target. Additionally, if this attack reduces the target to 50 hit points or fewer, you banish it. If the target is native to a different plane of existence than the one you\'re on, the target disappears, returning to its home plane. If the target is native to the plane you\'re on, the creature vanishes into a harmless demiplane. While there, the target is incapacitated. It remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.',
        'level': '5',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Abjuration',
        'concentration': True,

    },
    'bigbys hand': {
        'description': 'You create a large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell\'s duration, and it moves at your command, mimicking the movements of your own hand.The hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn\'t fill its space.\n\nWhen you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects with it.\n\nClenched Fist\nThe hand strikes one creature or object within 5 feet of it. Make a Melee Spell Attack for the hand using your game statistics. On a hit, the target takes 4d8 force damage.\n\nForceful Hand\nThe hand attempts to push a creature within 5 feet of it in a direction you choose. Make a check with the hand\'s Strength contested by the Strength (Athletics) check of the target. If the target is medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your Spellcasting Ability Modifier. The hand moves with the target to remain within 5 feet of it.\n\nGrasping Hand\nThe hand attempts to grapple a huge or smaller creature within 5 feet of it. You use the hand\'s Strength Score to resolve the grapple. If the target is medium or smaller, you have advantage on the check. While the hand is grappling the target, you can use a bonus action to have the hand crush it. When you do so, the target takes bludgeoning damage equal to 2d6 + your Spellcasting Ability Modifier.\n\nInterposing Hand\nThe hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover against the target. The target can\'t move through the hand\'s space if its Strength Score is less than or equal to the hand\'s Strength Score. If its Strength Score is higher than the hand\'s Strength Score, the target can move toward you through the hand\'s space, but that space is difficult terrain for the target.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage from the clenched fist option increases by 2d8 and the damage from the grasping hand increases by 2d6 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (an eggshell and a snakeskin glove)',
        'duration': '1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'circle of power': {
        'description': 'Divine energy radiates from you, distorting and diffusing magical energy within 30 feet of you. Until the spell ends, the sphere moves with you, centered on you. For the duration, each friendly creature in the area (including you) has advantage on Saving Throws against spells and other magical effects. Additionally, when an affected creature succeeds on a Saving Throw made against a spell or magical effect that allows it to make a Saving Throw to take only half damage, it instead takes no damage if it succeeds on the Saving Throw.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self (30-foot radius)',
        'components': 'V',
        'duration': '10 minutes',
        'school': 'Abjuration',
        'concentration': True,

    },
    'cloudkill': {
        'description': 'You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners. It lasts for the duration or until strong wind disperses the fog, ending the spell. Its area is heavily obscured.\n\nWhen a creature enters the spell\'s area for the first time on a turn or starts its turn there, that creature must make a Constitution Saving Throw. The creature takes 5d8 poison damage on a failed save, or half as much damage on a successful one. Creatures are affected even if they hold their breath or don\'t need to breathe.\n\nThe fog moves 10 feet away from you at the start of each of your turns, rolling along the surface of the ground. The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Conjuration',
        'concentration': True,

    },
    'commune with nature': {
        'description': 'You briefly become one with nature and gain knowledge of the surrounding territory. In the outdoors, the spell gives you knowledge of the land within 3 miles of you. In caves and other natural underground settings, the radius is limited to 300 feet. The spell doesn\'t function where nature has been replaced by construction, such as in dungeons and towns.\n\nYou instantly gain knowledge of up to three facts of your choice about any of the following subjects as they relate to the area:\n\n•terrain and bodies of water\n•prevalent plants, minerals, animals, or peoples\n•powerful celestials, fey, fiends, elementals, or undead\n•influence from other planes of existence\n•buildings\n\nFor example, you could determine the location of powerful undead in the area, the location of major sources of safe drinking water, and the location of any nearby towns.',
        'level': '5',
        'casting_time': '1 minute',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Divination',
        'concentration': False,
        'ritual': True
    },
    'commune': {
        'description': 'You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You must ask your questions before the spell ends. You receive a correct answer for each question.\n\nDivine beings aren\'t necessarily omniscient, so you might receive "unclear" as an answer if a question pertains to information that lies beyond the deity\'s knowledge. In a case where a one-word answer could be misleading or contrary to the deity\'s interests, the DM might offer a short phrase as an answer instead.\n\nIf you cast the spell two or more times before finishing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get no answer. The DM makes this roll in secret.',
        'level': '5',
        'casting_time': '1 minute',
        'range': 'Self',
        'components': 'V, S, M (incense and a vial of holy or unholy water)',
        'duration': '1 minute',
        'school': 'Divination',
        'concentration': False,
        'ritual': True
    },
    'cone of cold': {
        'description': 'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution Saving Throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one.\n\nA creature killed by this spell becomes a frozen statue until it thaws.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self (60-foot cone)',
        'components': 'V, S, M (a small crystal or glass cone)',
        'duration': 'Instantaneous',
        'school': 'Evocation',
        'concentration': False,

    },
    'conjure elemental': {
        'description': 'You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it. For example, a Fire Elemental emerges from a bonfire, and an Earth Elemental rises up from the ground. The elemental disappears when it drops to 0 hit points or when the spell ends.\n\nThe elemental is friendly to you and your companions for the duration. Roll initiative for the elemental, which has its own turns. It obeys any verbal commands that you issue to it (no action required by you). If you don\'t issue any commands to the elemental, it defends itself from hostile creatures but otherwise takes no actions.\n\nIf your concentration is broken, the elemental doesn\'t disappear. Instead, you lose control of the elemental, it becomes hostile toward you and your companions, and it might attack. An uncontrolled elemental can\'t be dismissed by you, and it disappears 1 hour after you summoned it.\n\nThe DM has the elemental\'s statistics.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the challenge rating increases by 1 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 minute',
        'range': '90 feet',
        'components': 'V, S, M (burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water)',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Conjuration',
        'concentration': True,

    },
    'conjure volley': {
        'description': 'You fire a piece of nonmagical ammunition from a ranged weapon or throw a nonmagical weapon into the air and choose a point within range. Hundreds of duplicates of the ammunition or weapon fall in a volley from above and then disappear. Each creature in a 40-foot-radius, 20-foot-high cylinder centered on that point must make a Dexterity Saving Throw. A creature takes 8d8 damage on a failed save, or half as much damage on a successful one. The damage type is the same as that of the ammunition or weapon.',
        'level': '5',
        'casting_time': '1 action',
        'range': '150 feet',
        'components': 'V, S, M (one piece of ammunition or one thrown weapon)',
        'duration': 'Instantaneous',
        'school': 'Conjuration',
        'concentration': False,

    },
    'contact other plane': {
        'description': 'You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane. Contacting this extraplanar Intelligence can strain or even break your mind. When you cast this spell, make a DC 15 Intelligence Saving Throw. On a failure, you take 6d6 psychic damage and are insane until you finish a long rest. While insane, you can\'t take actions, can\'t understand what other creatures say, can\'t read, and speak only in gibberish. A greater restoration spell cast on you ends this effect.\n\nOn a successful save, you can ask the entity up to five questions. You must ask your questions before the spell ends. The DM answers each question with one word, such as "yes," "no," "maybe," "never," "irrelevant," or "unclear" (if the entity doesn\'t know the answer to the question). If a one-word answer would be misleading, the DM might instead offer a short phrase as an answer.',
        'level': '5',
        'casting_time': '1 minute',
        'range': 'Self',
        'components': 'V',
        'duration': '1 minute',
        'school': 'Divination',
        'concentration': False,
        'ritual': True
    },
    'contagion': {
        'description': 'Your touch inflicts disease. Make a Melee Spell Attack against a creature within your reach. On a hit, the target is poisoned.\n\nAt the end of each of the poisoned target\'s turns, the target must make a Constitution Saving Throw. If the target succeeds on three of these saves, it is no longer poisoned, and the spell ends. If the target fails three of these saves, the target is no longer poisoned, but choose one of the diseases below. The target is subjected to the chosen disease for the spell\'s duration.\n\nSince this spell induces a natural disease in its target, any effect that removes a disease or otherwise ameliorates a disease\'s effects apply to it.\n\nBlinding Sickness\nPain grips the creature\'s mind, and its eyes turn milky white. The creature has disadvantage on Wisdom Checks and Wisdom Saving Throws and is blinded.\n\nFilth Fever\nA raging fever sweeps through the creature\'s body. The creature has disadvantage on Strength Checks, Strength Saving Throws, and Attack Rolls that use Strength.\n\nFlesh Rot\nThe creature\'s flesh decays. The creature has disadvantage on Charisma Checks and vulnerability to all damage.\n\nMindfire\nThe creature\'s mind becomes feverish. The creature has disadvantage on Intelligence Checks and Intelligence Saving Throws, and the creature behaves as if under the effects of the confusion spell during combat.\n\nSeizure\nThe creature is overcome with shaking. The creature has disadvantage on Dexterity Checks, Dexterity Saving Throws, and Attack Rolls that use Dexterity.\n\nSlimy Doom\nThe creature begins to bleed uncontrollably. The creature has disadvantage on Constitution Checks and Constitution Saving Throws. In addition, whenever the creature takes damage, it is stunned until the end of its next turn.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': '7 days',
        'school': 'Necromancy',
        'concentration': False,

    },
    'control winds': {
        'description': 'You take control of the air in a 100-foot cube that you can see within range. Choose one of the following effects when you cast the spell. The effect lasts for the spell\'s duration, unless you use your action on a later turn to switch to a different effect. You can also use your action to temporarily halt the effect or to restart one you\'ve halted.\n\nGusts\nA wind picks up within the cube, continually blowing in a horizontal direction you designate. You choose the intensity of the wind: calm, moderate, or strong. If the wind is moderate or strong, Ranged Weapon Attacks that pass through it or that are made against targets within the cube have disadvantage on their Attack Rolls. If the wind is strong, any creature moving against the wind must spend 1 extra foot of movement for each foot moved.\n\nDowndraft\nYou cause a sustained blast of strong wind to blow downward from the top of the cube. Ranged Weapon Attacks that pass through the cube or that are made against targets within it have disadvantage on their Attack Rolls. A creature must make a Strength Saving Throw if it flies into the cube for the first time on a turn or starts its turn there flying. On a failed save, the creature is knocked prone.\n\nUpdraft\nYou cause a sustained updraft within the cube, rising upward from the cube\'s bottom side. Creatures that end a fall within the cube take only half damage from the fall. When a creature in the cube makes a vertical jump, the creature can jump up to 10 feet higher than normal.',
        'level': '5',
        'casting_time': '1 action',
        'range': '300 feet',
        'components': 'V, S, M (a pinch of dust and a few drops of water)',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Transmutation',
        'concentration': True,

    },
    'creation': {
        'description': 'You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range: soft goods, rope, wood, or something similar. You can also use this spell to create mineral objects such as stone, crystal, or metal. The object created must be no larger than a 5-foot cube, and the object must be of a form and material that you have seen before.\n\nThe duration depends on the object\'s material. If the object is composed of multiple materials, use the shortest duration.\n\nCreation\n\n╔═══════════════════════╤════════════╗\n║ Material              │ Duration   ║\n╠═══════════════════════╪════════════╣\n║ Vegetable matter      │ 1 day      ║\n╟───────────────────────┼────────────╢\n║ Stone or crystal      │ 12 hours   ║\n╟───────────────────────┼────────────╢\n║ Precious metals       │ 1 hour     ║\n╟───────────────────────┼────────────╢\n║ Gems                  │ 10 minutes ║\n╟───────────────────────┼────────────╢\n║ Adamantine or mithral │ 1 minute   ║\n╚═══════════════════════╧════════════╝',
        'level': '5',
        'casting_time': '1 minute',
        'range': '30 feet',
        'components': 'V, S, M (a tiny piece of matter of the same type of the item you plan to create)',
        'duration': 'Special',
        'school': 'Illusion',
        'concentration': False,

    },
    'danse macabre': {
        'description': 'Threads of dark power leap from your fingers to pierce up to five small or medium corpses you can see within range. Each corpse immediately stands up and becomes undead. You decide whether it is a Zombie or a Skeleton (the statistics for Zombies and Skeletons are in the Monster Manual), and it gains a bonus to its Attack & Damage Rolls equal to your Spellcasting Ability Modifier.\n\nYou can use a bonus action to mentally command the creatures you make with this spell, issuing the same command to all of them. To receive the command, a creature must be within 60 feet of you. You decide what action the creatures will take and where they will move during their next turn, or you can issue a general command, such as to guard a chamber or passageway against your foes. If you issue no commands, the creatures do nothing except defend themselves against hostile creatures. Once given an order, the creatures continue to follow it until their task is complete.\n\nThe creatures are under your control until the spell ends, after which they become inanimate once more.\n\nWhen you cast this spell using a spell slot of 6th level or higher, you animate up to two additional corpses for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (a tiny silver or copper raven worth 100 gp, which the spell consumes)',
        'duration': '1 hour',
        'school': 'Necromancy',
        'concentration': True,

    },
    'dawn': {
        'description': 'The light of dawn shines down on a location you specify within range. Until the spell ends, a 30-foot-radius, 40-foot-high cylinder of bright light glimmers there. This light is sunlight.\n\nWhen the cylinder appears, each creature in it must make a Constitution Saving Throw, taking 4d10 radiant damage on a failed save, or half as much damage on a successful one. A creature must also make this Saving Throw whenever it ends its turn in the cylinder.\n\nIf you\'re within 60 feet of the cylinder, you can move it up to 60 feet as a bonus action on your turn.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self (60-foot radius)',
        'components': 'V, S',
        'duration': '1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'destructive wave': {
        'description': 'You strike the ground, creating a burst of divine energy that ripples outward from you. Each creature you choose within 30 feet of you must succeed on a Constitution Saving Throw or take 5d6 thunder damage, as well as 5d6 radiant or necrotic damage (your choice), and be knocked prone. A creature that succeeds on its Saving Throw takes half as much damage and isn\'t knocked prone.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self (30-foot radius)',
        'components': 'V',
        'duration': 'Instantaneous',
        'school': 'Evocation',
        'concentration': False,

    },
    'dispel evil and good': {
        'description': 'Shimmering energy surrounds and protects you from fey, undead, and creatures originating from beyond the Material Plane. For the duration, celestials, elementals, fey, fiends, and undead have disadvantage on Attack Rolls against you.\n\nYou can end the spell early by using either of the following special functions.\n\nBreak Enchantment\nAs your action, you touch a creature you can reach that is charmed, frightened, or possessed by a celestial, an elemental, a fey, a fiend, or an undead. The creature you touch is no longer charmed, frightened, or possessed by such creatures.\n\nDismissal\nAs your action, make a Melee Spell Attack against a celestial, an elemental, a fey, a fiend, or an undead you can reach. On a hit, you attempt to drive the creature back to its home plane. The creature must succeed on a Charisma Saving Throw or be sent back to its home plane (if it isn\'t there already). If they aren\'t on their home plane, undead are sent to the Shadowfell, and fey are sent to the Feywild.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S, M (holy water or powdered silver and iron worth at least 25 gp, which the spell consumes)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Abjuration',
        'concentration': True,

    },
    'dominate person': {
        'description': 'You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom Saving Throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the Saving Throw.\n\nWhile the target is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature," "Run over there," or "Fetch that object." If the creature completes the order and doesn\'t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn\'t do anything that you don\'t allow it to do. During this time you can also cause the creature to use a reaction, but this requires you to use your own reaction as well.\n\nEach time the target takes damage, it makes a new Wisdom Saving Throw against the spell. If the Saving Throw succeeds, the spell ends.\n\nWhen you cast this spell using a 6th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 7th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 8th level or higher, the duration is concentration, up to 8 hours.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'dream': {
        'description': 'This spell shapes a creature\'s dreams. Choose a creature known to you as the target of this spell. The target must be on the same plane of existence as you. Creatures that don\'t sleep, such as elves, can\'t be contacted by this spell. You, or a willing creature you touch, enters a trance state, acting as a messenger. While in the trance, the messenger is aware of his or her surroundings, but can\'t take actions or move.\n\nIf the target is asleep, the messenger appears in the target\'s dreams and can converse with the target as long as it remains asleep, through the duration of the spell. The messenger can also shape the environment of the dream, creating landscapes, objects, and other images. The messenger can emerge from the trance at any time, ending the effect of the spell early. The target recalls the dream perfectly upon waking. If the target is awake when you cast the spell, the messenger knows it, and can either end the trance (and the spell) or wait for the target to fall asleep, at which point the messenger appears in the target\'s dreams.\n\nYou can make the messenger appear monstrous and terrifying to the target. If you do, the messenger can deliver a message of no more than ten words and then the target must make a Wisdom Saving Throw. On a failed save, echoes of the phantasmal monstrosity spawn a nightmare that lasts the duration of the target\'s sleep and prevents the target from gaining any benefit from that rest. In addition, when the target wakes up, it takes 3d6 psychic damage.\n\nIf you have a body part, lock of hair, clipping from a nail, or similar portion of the target\'s body, the target makes its Saving Throw with disadvantage.',
        'level': '5',
        'casting_time': '1 minute',
        'range': 'Special',
        'components': 'V, S, M (a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird)',
        'duration': '8 hours',
        'school': 'Illusion',
        'concentration': False,

    },
    'enervation': {
        'description': 'A tendril of inky darkness reaches out from you, touching a creature you can see within range to drain life from it. The target must make a Dexterity Saving Throw. On a successful save, the target takes 2d8 necrotic damage, and the spell ends. On a failed save, the target takes 4d8 necrotic damage, and until the spell ends, you can use your action on each of your turns to automatically deal 4d8 necrotic damage to the target. The spell ends if you use your action to do anything else, if the target is ever outside the spell\'s range, or if the target has total cover from you.\n\nWhenever the spell deals damage to a target, you regain hit points equal to half the amount of necrotic damage the target takes.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Necromancy',
        'concentration': False,

    },
    'far step': {
        'description': 'You teleport up to 60 feet to an unoccupied space you can see. On each of your turns before the spell ends, you can use a bonus action to teleport in this way again.',
        'level': '5',
        'casting_time': '1 bonus action',
        'range': 'Self',
        'components': 'V',
        'duration': '1 minute',
        'school': 'Conjuration',
        'concentration': True,

    },
    'flame strike': {
        'description': 'A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity Saving Throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much damage on a successful one.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the fire damage or the radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S, M (pinch of sulfur)',
        'duration': 'Instantaneous',
        'school': 'Evocation',
        'concentration': False,

    },
    'geas': {
        'description': 'You place a magical command on a creature that you can see within range, forcing it to carry out some service or refrain from some action or course of activity as you decide. If the creature can understand you, it must succeed on a Wisdom Saving Throw or become charmed by you for the duration. While the creature is charmed by you, it takes 5d10 psychic damage each time it acts in a manner directly counter to your instructions, but no more than once each day. A creature that can\'t understand you is unaffected by the spell.\n\nYou can issue any command you choose, short of an activity that would result in certain death. Should you issue a suicidal command, the spell ends.\n\nYou can end the spell early by using an action to dismiss it. A remove curse, greater restoration, or wish spell also ends it.\n\nWhen you cast this spell using a spell slot of 7th or 8th level, the duration is 1 year. When you cast this spell using a spell slot of 9th level, the spell lasts until it is ended by one of the spells mentioned above.',
        'level': '5',
        'casting_time': '1 minute',
        'range': '60 feet',
        'components': 'V',
        'duration': '30 days',
        'school': 'Enchantment',
        'concentration': False,

    },
    'greater restoration': {
        'description': 'You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target\'s exhaustion level by one, or end one of the following effects on the target:\n\n•One effect that charmed or petrified the target\n•One curse, including the target\'s attunement to a cursed magic item\n•Any reduction to one of the target\'s Ability Scores\n•One effect reducing the target\'s hit point maximum',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S, M (diamond dust worth at least 100 gp, which the spell consumes)',
        'duration': 'Instantaneous',
        'school': 'Abjuration',
        'concentration': False,

    },
    'hallow': {
        'description': 'You touch a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 60 feet, and the spell fails if the radius includes an area already under the effect a hallow spell. The affected area is subject to the following effects.\n\nFirst, celestials, elementals, fey, fiends, and undead can\'t enter the area, nor can such creatures charm, frighten, or possess creatures within it. Any creature charmed, frightened, or possessed by such a creature is no longer charmed, frightened, or possessed upon entering the area. You can exclude one or more of those types of creatures from this effect.\n\nSecond, you can bind an extra effect to the area. Choose the effect from the following list, or choose an effect offered by the DM. Some of these effects apply to creatures in the area; you can designate whether the effect applies to all creatures, creatures that follow a specific deity or leader, or creatures of a specific sort, such as orcs or trolls. When a creature that would be affected enters the spell\'s area for the first time on a turn or starts its turn there, it can make a Charisma Saving Throw. On a success, the creature ignores the extra effect until it leaves the area.\n\nCourage\nAffected creatures can\'t be frightened while in the area.\n\nDarkness\nDarkness fills the area. Normal light, as well as magical light created by spells of a lower level than the slot you used to cast this spell, can\'t illuminate the area.\n\nDaylight\nBright light fills the area. Magical darkness created by spells of a lower level than the slot you used to cast this spell can\'t extinguish the light.\n\nEnergy Protection\nAffected creatures in the area have resistance to one damage type of your choice, except for bludgeoning, piercing, or slashing.\n\nEnergy Vulnerability\nAffected creatures in the area have vulnerability to one damage type of your choice, except for bludgeoning, piercing, or slashing.\n\nEverlasting Rest\nDead bodies interred in the area can\'t be turned into undead.\n\nExtradimensional Interference\nAffected creatures can\'t move or travel using teleportation or by extradimensional or interplanar means.\n\nFear\nAffected creatures are frightened while in the area.\n\nSilence\nNo sound can emanate from within the area, and no sound can reach into it.\n\nTongues\nAffected creatures can communicate with any other creature in the area, even if they don\'t share a common language.',
        'level': '5',
        'casting_time': '24 hours',
        'range': 'Touch',
        'components': 'V, S, M (herbs, oils, and incense worth at least 1,000 gp, which the spell consumes)',
        'duration': 'Until dispelled',
        'school': 'Evocation',
        'concentration': False,

    },
    'hold monster': {
        'description': 'Choose a creature that you can see within range. The target must succeed on a Wisdom Saving Throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom Saving Throw. On a success, the spell ends on the target.\n\nWhen you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th. The creatures must be within 30 feet of each other when you target them.',
        'level': '5',
        'casting_time': '1 action',
        'range': '90 feet',
        'components': 'V, S, M (a small, straight piece of iron)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'holy weapon': {
        'description': 'You imbue a weapon you touch with holy power. Until the spell ends, the weapon emits bright light in a 30-foot radius and dim light for an additional 30 feet. In addition, Weapon Attacks made with it deal an extra 2d8 radiant damage on a hit. If the weapon isn\'t already a magic weapon, it becomes one for the duration.\n\nAs a bonus action on your turn, you can dismiss this spell and cause the weapon to emit a burst of radiance. Each creature of your choice that you can see within 30 feet of you must make a Constitution Saving Throw. On a failed save, a creature takes 4d8 radiant damage, and it is blinded for 1 minute. On a successful save, a creature takes half as much damage and isn\'t blinded. At the end of each of its turns, a blinded creature can make a Constitution Saving Throw, ending the effect on itself on a success.',
        'level': '5',
        'casting_time': '1 bonus action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Evocation',
        'concentration': True,

    },
    'immolation': {
        'description': 'Flames wreathe one creature you can see within range. The target must make a Dexterity Saving Throw. It takes 8d6 fire damage on a failed save, or half as much damage on a successful one. On a failed save, the target also burns for the spell\'s duration. The burning target sheds bright light in a 30-foot radius and dim light for an additional 30 feet. At the end of each of its turns, the target repeats the Saving Throw. It takes 4d6 fire damage on a failed save, and the spell ends on a successful one. These magical flames can\'t be extinguished by nonmagical means.\n\nIf damage from this spell kills a target, the target is turned to ash.',
        'level': '5',
        'casting_time': '1 action',
        'range': '90 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'infernal calling': {
        'description': 'Uttering a dark incantation, you summon a devil from the Nine Hells. You choose the devil\'s type, which must be one of challenge rating 6 or lower, such as a Barbed Devil or a Bearded Devil. The devil appears in an unoccupied space that you can see within range. The devil disappears when it drops to 0 hit points or when the spell ends.\n\nThe devil is unfriendly toward you and your companions. Roll initiative for the devil, which has its own turns. It is under the Dungeon Master\'s control and acts according to its nature on each of its turns, which might result in its attacking you if it thinks it can prevail, or trying to tempt you to undertake an evil act in exchange for limited service. The DM has the creature\'s statistics.\n\nOn each of your turns, you can try to issue a verbal command to the devil (no action required by you). It obeys the command if the likely outcome is in accordance with its desires, especially if the result would draw you toward evil. Otherwise, you must make a Charisma (Deception, Intimidation, or Persuasion) check contested by its Wisdom (Insight) check. You make the check with advantage if you say the devil\'s true name. If your check fails, the devil becomes immune to your verbal commands for the duration of the spell, though it can still carry out your commands if it chooses. If your check succeeds, the devil carries out your command—such as "attack my enemies," "explore the room ahead," or "bear this message to the queen"—until it completes the activity, at which point it returns to you to report having done so.\n\nIf your concentration ends before the spell reaches its full duration, the devil doesn\'t disappear if it has become immune to your verbal commands. Instead, it acts in whatever manner it chooses for 3d6 minutes, and then it disappears.\n\nIf you possess an individual devil\'s talisman, you can summon that devil if it is of the appropriate challenge rating plus 1, and it obeys all your commands, with no Charisma Checks required.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the challenge rating increases by 1 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 minute',
        'range': '90 feet',
        'components': 'V, S, M (a ruby worth at least 999 gp, which is consumed in the casting)',
        'duration': 'Instantaneous',
        'school': 'Conjuration',
        'concentration': False,

    },
    'insect plague': {
        'description': 'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range. The sphere spreads around corners. The sphere remains for the duration, and its area is lightly obscured. The sphere\'s area is difficult terrain.\n\nWhen the area appears, each creature in it must make a Constitution Saving Throw. A creature takes 4d10 piercing damage on a failed save, or half as much damage on a successful one. A creature must also make this Saving Throw when it enters the spell\'s area for the first time on a turn or ends its turn there.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d10 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '300 feet',
        'components': 'V, S, M (a few grains of sugar, some kernels of grain, and a smear of fat)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Conjuration',
        'concentration': True,

    },
    'intellect fortress': {
        'description': 'You create a faintly shimmering barrier of protective psychic power around you. For the duration, you have advantage on all Saving Throws.\n\nWhen another creature that you can see within 30 feet of you fails a Saving Throw, you can use your reaction to allow them to reroll the save. They must use the new roll.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 hour',
        'school': 'Abjuration',
        'concentration': True,

    },
    'legend lore': {
        'description': 'Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known. If the thing you named isn\'t of legendary importance, you gain no information. The more information you already have about the thing, the more precise and detailed the information you receive is.\n\nThe information you learn is accurate but might be couched in figurative language. For example, if you have a mysterious magic axe on hand, the spell might yield this information: "Woe to the evildoer whose hand touches the axe, for even the haft slices the hand of the evil ones. Only a true Child of Stone, lover and beloved of Moradin, may awaken the true powers of the axe, and only with the sacred word Rudnogg on the lips."',
        'level': '5',
        'casting_time': '10 minutes',
        'range': 'Self',
        'components': 'V, S, M (incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each)',
        'duration': 'Instantaneous',
        'school': 'Divination',
        'concentration': False,

    },
    'maelstrom': {
        'description': 'A swirling mass of 5-foot-deep water appears in a 30-foot radius centered on a point you can see within range. The point must be on the ground or in a body of water. Until the spell ends, that area is difficult terrain, and any creature that starts its turn there must succeed on a Strength Saving Throw or take 6d6 bludgeoning damage and be pulled 10 feet toward the center.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (a piece of a tornado)',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    },
    'mass cure wounds': {
        'description': 'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your Spellcasting Ability Modifier. This spell has no effect on undead or constructs.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Evocation',
        'concentration': False,

    },
    'mislead': {
        'description': 'You become invisible at the same time that an illusory double of you appears where you are standing. The double lasts for the duration, but the invisibility ends if you attack or cast a spell.\n\nYou can use your action to move your illusory double up to twice your speed and make it gesture, speak, and behave in whatever way you choose.\n\nYou can see through its eyes and hear through its ears as if you were located where it is. On each of your turns as a bonus action, you can switch from using its senses to using your own, or back again. While you are using its senses, you are blinded and deafened in regard to your own surroundings.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'S',
        'duration': '1 hour',
        'school': 'Illusion',
        'concentration': False,

    },
    'modify memory': {
        'description': 'You attempt to reshape another creature\'s memories. One creature that you can see must make a Wisdom Saving Throw. If you are fighting the creature, it has advantage on the Saving Throw. On a failed save, the target becomes charmed by you for the duration. The charmed target is incapacitated and unaware of its surroundings, though it can still hear you. If it takes any damage or is targeted by another spell, this spell ends, and none of the target\'s memories are modified.\n\nWhile this charm lasts, you can affect the target\'s memory of an event that it experienced within the last 24 hours and that lasted no more than 10 minutes. You can permanently eliminate all memory of the event, allow the target to recall the event with perfect clarity and exacting detail, change its memory of the details of the event, or create a memory of some other event.\n\nYou must speak to the target to describe how its memories are affected, and it must be able to understand your language for the modified memories to take root. Its mind fills in any gaps in the details of your description. If the spell ends before you have finished describing the modified memories, the creature\'s memory isn\'t altered. Otherwise, the modified memories take hold when the spell ends.\n\nA modified memory doesn\'t necessarily affect how a creature behaves, particularly if the memory contradicts the creature\'s natural inclinations, alignment, or beliefs. An illogical modified memory, such as implanting a memory of how much the creature enjoyed dousing itself in acid, is dismissed, perhaps as a bad dream. The DM might deem a modified memory too nonsensical to affect a creature in a significant manner.\n\nA remove curse or greater restoration spell cast on the target restores the creature\'s true memory.\n\nIf you cast this spell using a spell slot of 6th level or higher, you can alter the target\'s memories of an event that took place up to 7 days ago (6th level), 30 days ago (7th level), 1 year ago (8th level), or any time in the creature\'s past (9th level).',
        'level': '5',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Enchantment',
        'concentration': True,

    },
    'negative energy flood': {
        'description': 'You send ribbons of negative energy at one creature you can see within range. Unless the target is undead, it must make a Constitution Saving Throw, taking 5d12 necrotic damage on a failed save, or half as much damage on a successful one. A target killed by this damage rises up as a zombie at the start of your next turn. The zombie pursues whatever creature it can see that is closest to it. Statistics for the zombie are in the Monster Manual.\n\nIf you target an undead with this spell, the target doesn\'t make a Saving Throw. Instead, roll 5d12. The target gains half the total as temporary hit points.',
        'level': '6th-level',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Necromancy',
        'concentration': False,

    },
    'passwall': {
        'description': 'A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface (such as a wall, a ceiling, or a floor) within range, and lasts for the duration. You choose the opening\'s dimensions: up to 5 feet wide, 8 feet tall, and 20 feet deep. The passage creates no instability in a structure surrounding it.\n\nWhen the opening disappears, any creatures or objects still in the passage created by the spell are safely ejected to an unoccupied space nearest to the surface on which you cast the spell.',
        'level': '5',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (a pinch of sesame seeds)',
        'duration': '1 hour',
        'school': 'Transmutation',
        'concentration': False,

    },
    'planar binding': {
        'description': 'With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting of the spell. (Typically, the creature is first summoned into the center of an inverted magic circle in order to keep it trapped while this spell is cast.) At the completion of the casting, the target must make a Charisma Saving Throw. On a failed save, it is bound to serve you for the duration. If the creature was summoned or created by another spell, that spell\'s duration is extended to match the duration of this spell.\n\nA bound creature must follow your instructions to the best of its ability. You might command the creature to accompany you on an adventure, to guard a location, or to deliver a message. The creature obeys the letter of your instructions, but if the creature is hostile to you, it strives to twist your words to achieve its own objectives. If the creature carries out your instructions completely before the spell ends, it travels to you to report this fact if you are on the same plane of existence. If you are on a different plane of existence, it returns to the place where you bound it and remains there until the spell ends.\n\nWhen you cast this spell using a spell slot of a higher level, the duration increases to 10 days with a 6th-level slot, to 30 days with a 7th-level slot, to 180 days with an 8th-level slot, and to a year and a day with a 9th-level spell slot.',
        'level': '5',
        'casting_time': '1 hour',
        'range': '60 feet',
        'components': 'V, S, M (a jewel worth at least 1,000 gp, which the spell consumes)',
        'duration': '24 hours',
        'school': 'Abjuration',
        'concentration': False,

    },
    'raise dead': {
        'description': 'You return a dead creature you touch to life, provided that it has been dead no longer than 10 days. If the creature\'s soul is both willing and at liberty to rejoin the body, the creature returns to life with 1 hit point.\n\nThis spell also neutralizes any poisons and cures nonmagical diseases that affected the creature at the time it died. This spell doesn\'t, however, remove magical diseases, curses, or similar effects; if these aren\'t first removed prior to casting the spell, they take effect when the creature returns to life. The spell can\'t return an undead creature to life.\n\nThis spell closes all mortal wounds, but it doesn\'t restore missing body parts. If the creature is lacking body parts or organs integral for its survival—its head, for instance—the spell automatically fails.\n\nComing back from the dead is an ordeal. The target takes a -4 penalty to all Attack Rolls, Saving Throws, and Ability Checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.',
        'level': '5',
        'casting_time': '1 hour',
        'range': 'Touch',
        'components': 'V, S, M (a diamond worth at least 500 gp, which the spell consumes)',
        'duration': 'Instantaneous',
        'school': 'Necromancy',
        'concentration': False,

    },
    "Rary's Telepathic Bond": {
        'description': 'You forge a telepathic link among up to eight willing creatures of your choice within range, psychically linking each creature to all the others for the duration. Creatures with Intelligence Scores of 2 or less aren\'t affected by this spell.\n\nUntil the spell ends, the targets can communicate telepathically through the bond whether or not they have a common language. The communication is possible over any distance, though it can\'t extend to other planes of existence.',
        'level': '5',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S, M (pieces of eggshell from two different kinds of creatures)',
        'duration': '1 hour',
        'school': 'Divination',
        'concentration': False,

    },
    'reincarnate': {
        'description': 'You touch a dead humanoid or a piece of a dead humanoid. Provided that the creature has been dead no longer than 10 days, the spell forms a new adult body for it and then calls the soul to enter that body. If the target\'s soul isn\'t free or willing to do so, the spell fails.\n\nThe magic fashions a new body for the creature to inhabit, which likely causes the creature\'s race to change. The DM rolls a d100 and consults the following table to determine what form the creature takes when restored to life, or the DM chooses a form.\n\nReincarnate Races\n\n╔═══════╤═════════════════════╗\n║ d100  │ Race                ║\n╠═══════╪═════════════════════╣\n║ 1-4   │ Dragonborn          ║\n╟───────┼─────────────────────╢\n║ 5-13  │ Dwarf, Hill         ║\n╟───────┼─────────────────────╢\n║ 14-21 │ Dwarf, Mountain     ║\n╟───────┼─────────────────────╢\n║ 22-25 │ Elf, Dark           ║\n╟───────┼─────────────────────╢\n║ 26-34 │ Elf, High           ║\n╟───────┼─────────────────────╢\n║ 35-42 │ Elf, Wood           ║\n╟───────┼─────────────────────╢\n║ 43-46 │ Gnome, Forest       ║\n╟───────┼─────────────────────╢\n║ 47-52 │ Gnome, Rock         ║\n╟───────┼─────────────────────╢\n║ 53-56 │ Half-Elf            ║\n╟───────┼─────────────────────╢\n║ 57-60 │ Half-Orc            ║\n╟───────┼─────────────────────╢\n║ 61-68 │ Halfling, Lightfoot ║\n╟───────┼─────────────────────╢\n║ 69-76 │ Halfling, Stout     ║\n╟───────┼─────────────────────╢\n║ 77-96 │ Human               ║\n╟───────┼─────────────────────╢\n║ 97-0  │ Tiefling            ║\n╚═══════╧═════════════════════╝\n\nThe reincarnated creature recalls its former life and experiences. It retains the capabilities it had in its original form, except it exchanges its original race for the new one and changes its racial traits accordingly.',
        'level': '5',
        'casting_time': '1 hour',
        'range': 'Touch',
        'components': 'V, S, M (rare oils and unguents worth at least 1,000 gp, which the spell consumes)',
        'duration': 'Instantaneous',
        'school': 'Transmutation',
        'concentration': False,

    },
    'scrying': {
        'description': 'You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom Saving Throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you\'re casting this spell, it can fail the Saving Throw voluntarily if it wants to be observed.\n\nKnowledge of Target\n\n╔═══════════════════════════════════════════╤═══════════════╗\n║ Knowledge                                 │ Save Modifier ║\n╠═══════════════════════════════════════════╪═══════════════╣\n║ Secondhand (you have heard of the target) │ +5            ║\n╟───────────────────────────────────────────┼───────────────╢\n║ Firsthand (you have met the target)       │ +0            ║\n╟───────────────────────────────────────────┼───────────────╢\n║ Familiar (you know the target well)       │ -5            ║\n╚═══════════════════════════════════════════╧═══════════════╝\n\nConnection to Target\n\n╔═══════════════════════════════════════════════════╤═══════════════╗\n║ Connection                                        │ Save Modifier ║\n╠═══════════════════════════════════════════════════╪═══════════════╣\n║ Likeness or picture                               │ -2            ║\n╟───────────────────────────────────────────────────┼───────────────╢\n║ Possession or garment                             │ -4            ║\n╟───────────────────────────────────────────────────┼───────────────╢\n║ Body part, lock of hair, bit of nail, or the like │ -10           ║\n╚═══════════════════════════════════════════════════╧═══════════════╝\n\nOn a successful save, the target isn\'t affected, and you can\'t use this spell against it again for 24 hours.\n\nOn a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. A creature that can see invisible objects sees the sensor as a luminous orb about the size of your fist.\n\nOn a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. A creature that can see invisible objects sees the sensor as a luminous orb about the size of your fist.',
        'level': '5',
        'casting_time': '10 minutes',
        'range': 'Self',
        'components': 'V, S, M (a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Divination',
        'concentration': True,

    },
    'seeming': {
        'description': 'This spell allows you to change the appearance of any number of creatures that you can see within range. You give each target you choose a new, illusory appearance. An unwilling target can make a Charisma Saving Throw, and if it succeeds, it is unaffected by this spell.\n\nThe spell disguises physical appearance as well as clothing, armor, weapons, and equipment. You can make each creature seem 1 foot shorter or taller and appear thin, fat, or in between. You can\'t change a target\'s body type, so you must choose a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you. The spell lasts for the duration, unless you use your action to dismiss it sooner.\n\nThe changes wrought by this spell fail to hold up to physical inspection. For example, if you use this spell to add a hat to a creature\'s outfit, objects pass through the hat, and anyone who touches it would feel nothing or would feel the creature\'s head and hair. If you use this spell to appear thinner than you are, the hand of someone who reaches out to touch you would bump into you while it was seemingly still in midair.\n\nA creature can use its action to inspect a target and make an Intelligence (Investigation) check against your Spell Save DC. If it succeeds, it becomes aware that the target is disguised.',
        'level': '5',
        'casting_time': '1 action',
        'range': '30 feet',
        'components': 'V, S',
        'duration': '8 hours',
        'school': 'Illusion',
        'concentration': False,

    },
    'skill empowerment': {
        'description': 'Your magic deepens a creature\'s understanding of its own talent. You touch one willing creature and give it expertise in one skill of your choice; until the spell ends, the creature doubles its proficiency bonus for Ability Checks it makes that use the chosen skill.\n\nYou must choose a skill in which the target is proficient and that isn\'t already benefiting from an effect, such as Expertise, that doubles its proficiency bonus.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Touch',
        'components': 'V, S',
        'duration': '1 hour',
        'school': 'Transmutation',
        'concentration': False,

    },
    'steel wind strike': {
        'description': 'You flourish the weapon used in the casting and then vanish to strike like the wind. Choose up to five creatures you can see within range. Make a Melee Spell Attack against each target. On a hit, a target takes 6d10 force damage.\n\nYou can then teleport to an unoccupied space you can see within 5 feet of one of the targets you hit or missed.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self (5-foot radius)',
        'components': 'V, S',
        'duration': 'Instantaneous',
        'school': 'Conjuration',
        'concentration': False,

    },
    'swift quiver': {
        'description': 'You transmute your quiver so it produces an endless supply of nonmagical ammunition, which seems to leap into your hand when you reach for it.\n\nOn each of your turns until the spell ends, you can use a bonus action to make two attacks with a weapon that uses ammunition from the quiver. Each time you make such a Ranged Attack, your quiver magically replaces the piece of ammunition you used with a similar piece of nonmagical ammunition. Any pieces of ammunition created by this spell disintegrate when the spell ends. If the quiver leaves your possession, the spell ends.',
        'level': '5',
        'casting_time': '1 bonus action',
        'range': 'Touch',
        'components': 'V, S, M (a quiver containing at least one piece of ammunition)',
        'duration': '1 minute',
        'school': 'Transmutation',
        'concentration': False,

    },
    'synaptic static': {
        'description': 'You choose a point within range and cause psychic energy to explode there. Each creature in a 20-foot-radius sphere centered on that point must make an Intelligence Saving Throw. A creature with an Intelligence Score of 2 or lower can\'t be affected by this spell. A target takes 8d6 psychic damage on a failed save, or half as much damage on a successful one.\n\nAfter a failed save, a target has muddled thoughts for 1 minute. During that time, it rolls a d6 and subtracts the number rolled from all its Attack Rolls and Ability Checks, as well as its Constitution Saving Throws to maintain concentration. The target can make an Intelligence Saving Throw at the end of each of its turns, ending the effect on itself on a success.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (a bit of fleece)',
        'duration': 'Instantaneous',
        'school': 'Enchantment',
        'concentration': False,

    },
    'telekinesis': {
        'description': 'You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as your action each round for the duration, you can exert your will on one creature or object that you can see within range, causing the appropriate effect below. You can affect the same target round after round, or choose a new one at any time. If you switch targets, the prior target is no longer affected by the spell.\n\nCreature\nYou can try to move a huge or smaller creature. Make an Ability Check with your spellcasting ability contested by the creature\'s Strength Check. If you win the contest, you move the creature up to 30 feet in any direction, including upward but not beyond the range of this spell. Until the end of your next turn, the creature is restrained in your telekinetic grip. A creature lifted upward is suspended in mid-air.\n\nOn subsequent rounds, you can use your action to attempt to maintain your telekinetic grip on the creature by repeating the contest.\n\nObject\nYou can try to move an object that weighs up to 1,000 pounds. If the object isn\'t being worn or carried, you automatically move it up to 30 feet in any direction, but not beyond the range of this spell.\n\nIf the object is worn or carried by a creature, you must make an Ability Check with your spellcasting ability contested by that creature\'s Strength Check. If you succeed, you pull the object away from that creature and can move it up to 30 feet in any direction but not beyond the range of this spell.\n\nYou can exert fine control on objects with your telekinetic grip, such as manipulating a simple tool, opening a door or a container, stowing or retrieving an item from an open container, or pouring the contents from a vial.',
        'level': '5',
        'casting_time': '1 action',
        'range': '60 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Transmutation',
        'concentration': True,

    },
    'teleportation circle': {
        'description': 'As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied.\n\nMany major temples, guilds, and other important places have permanent teleportation circles inscribed somewhere within their confines. Each such circle includes a unique sigil sequence—a string of magical runes arranged in a particular pattern. When you first gain the ability to cast this spell, you learn the sigil sequences for two destinations on the Material Plane, determined by the DM. You can learn additional sigil sequences during your adventures. You can commit a new sigil sequence to memory after studying it for 1 minute.\n\nYou can create a permanent teleportation circle by casting this spell in the same location every day for one year. You need not use the circle to teleport when you cast the spell in this way.',
        'level': '5',
        'casting_time': '1 minute',
        'range': '10 feet',
        'components': 'V, M (rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes)',
        'duration': '1 round',
        'school': 'Conjuration',
        'concentration': False,

    },
    'transmute rock': {
        'description': 'You choose an area of stone or mud that you can see that fits within a 40-foot cube and is within range, and choose one of the following effects.\n\nTransmute Rock to Mud\nNonmagical rock of any sort in the area becomes an equal volume of thick, flowing mud that remains for the spell\'s duration.\n\nThe ground in the spell\'s area becomes muddy enough that creatures can sink into it. Each foot that a creature moves through the mud costs 4 feet of movement, and any creature on the ground when you cast the spell must make a Strength Saving Throw. A creature must also make the Saving Throw when it moves into the area for the first time on a turn or ends its turn there. On a failed save, a creature sinks into the mud and is restrained, though it can use an action to end the restrained condition on itself by pulling itself free of the mud.\n\nIf you cast the spell on a ceiling, the mud falls. Any creature under the mud when it falls must make a Dexterity Saving Throw. A creature takes 4d8 bludgeoning damage on a failed save, or half as much damage on a successful one.\n\nTransmute Mud to Rock\nNonmagical mud or quicksand in the area no more than 10 feet deep transforms into soft stone for the spell\'s duration. Any creature in the mud when it transforms must make a Dexterity Saving Throw. On a successful save, a creature is shunted safely to the surface in an unoccupied space. On a failed save, a creature becomes restrained by the rock. A restrained creature, or another creature within reach, can use an action to try to break the rock by succeeding on a DC 20 Strength Check or by dealing damage to it. The rock has AC 15 and 25 hit points, and it is immune to poison and psychic damage.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (clay and water)',
        'duration': 'Instantaneous',
        'school': 'Transmutation',
        'concentration': False,

    },
    'tree stride': {
        'description': 'You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 feet. Both trees must be living and at least the same size as you. You must use 5 feet of movement to enter a tree. You instantly know the location of all other trees of the same kind within 500 feet and, as part of the move used to enter the tree, can either pass into one of those trees or step out of the tree you\'re in. You appear in a spot of your choice within 5 feet of the destination tree, using another 5 feet of movement. If you have no movement left, you appear within 5 feet of the tree you entered.\n\nYou can use this transportation ability once per round for the duration. You must end each turn outside a tree.',
        'level': '5',
        'casting_time': '1 action',
        'range': 'Self',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Conjuration',
        'concentration': True,

    },
    'wall of force': {
        'description': 'An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. Each panel must be contiguous with another panel. In any form, the wall is 1/4 inch thick. It lasts for the duration. If the wall cuts through a creature\'s space when it appears, the creature is pushed to one side of the wall (your choice which side).\n\nNothing can physically pass through the wall. It is immune to all damage and can\'t be dispelled by dispel magic. A disintegrate spell destroys the wall instantly, however. The wall also extends into the Ethereal Plane, blocking ethereal travel through the wall.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (a pinch of powder made by crushing a clear gemstone)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Evocation',
        'concentration': True,

    },
    'wall of light': {
        'description': 'A shimmering wall of bright light appears at a point you choose within range. The wall appears in any orientation you choose: horizontally, vertically, or diagonally. It can be free floating, or it can rest on a solid surface. The wall can be up to 60 feet long, 10 feet high, and 5 feet thick. The wall blocks line of sight, but creatures and objects can pass through it. It emits bright light out to 120 feet and dim light for an additional 120 feet.\n\nWhen the wall appears, each creature in its area must make a Constitution Saving Throw. On a failed save, a creature takes 4d8 radiant damage, and it is blinded for 1 minute. On a successful save, it takes half as much damage and isn\'t blinded. A blinded creature can make a Constitution Saving Throw at the end of each of its turns, ending the effect on itself on a success.\n\nA creature that ends its turn in the wall\'s area takes 4d8 radiant damage.\n\nUntil the spell ends, you can use an action to launch a beam of radiance from the wall at one creature you can see within 60 feet of it. Make a Ranged Spell Attack. On a hit, the target takes 4d8 radiant damage. Whether you hit or miss, reduce the length of the wall by 10 feet. If the wall\'s length drops to 0 feet, the spell ends.\n\nWhen you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (a hand mirror)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Evocation',
        'concentration': True,

    },
    'wall of stone': {
        'description': 'A nonmagical wall of solid stone springs into existence at a point you choose within range. The wall is 6 inches thick and is composed of ten 10-foot-by-10-foot panels. Each panel must be contiguous with at least one other panel. Alternatively, you can create 10-foot-by-20-foot panels that are only 3 inches thick.\n\nIf the wall cuts through a creature\'s space when it appears, the creature is pushed to one side of the wall (your choice). If a creature would be surrounded on all sides by the wall (or the wall and another solid surface), that creature can make a Dexterity Saving Throw. On a success, it can use its reaction to move up to its speed so that it is no longer enclosed by the wall.\n\nThe wall can have any shape you desire, though it can\'t occupy the same space as a creature or object. The wall doesn\'t need to be vertical or rest on any firm foundation. It must, however, merge with and be solidly supported by existing stone. Thus, you can use this spell to bridge a chasm or create a ramp.\n\nIf you create a span greater than 20 feet in length, you must halve the size of each panel to create supports. You can crudely shape the wall to create crenellations, battlements, and so on.\n\nThe wall is an object made of stone that can be damaged and thus breached. Each panel has AC 15 and 30 hit points per inch of thickness. Reducing a panel to 0 hit points destroys it and might cause connected panels to collapse at the DM\'s discretion.\n\nIf you maintain your concentration on this spell for its whole duration, the wall becomes permanent and can\'t be dispelled. Otherwise, the wall disappears when the spell ends.',
        'level': '5',
        'casting_time': '1 action',
        'range': '120 feet',
        'components': 'V, S, M (a small block of granite)',
        'duration': 'Concentration, up to 10 minutes',
        'school': 'Evocation',
        'concentration': True,

    },
    'wrath of nature': {
        'description': 'You call out to the spirits of nature to rouse them against your enemies. Choose a point you can see within range. The spirits cause trees, rocks, and grasses in a 60-foot cube centered on that point to become animated until the spell ends.\n\nGrasses and Undergrowth\nAny area of ground in the cube that is covered by grass or undergrowth is difficult terrain for your enemies.\n\nTrees\nAt the start of each of your turns, each of your enemies within 10 feet of any tree in the cube must succeed on a Dexterity Saving Throw or take 4d6 slashing damage from whipping branches.\n\nRoots and Vines\nAt the end of each of your turns, one creature of your choice that is on the ground in the cube must succeed on a Strength Saving Throw or become restrained until the spell ends. A restrained creature can use an action to make a Strength (Athletics) check against your Spell Save DC, ending the effect on itself on a success.\n\nRocks\nAs a bonus action on your turn, you can cause a loose rock in the cube to launch at a creature you can see in the cube. Make a Ranged Spell Attack against the target. On a hit, the target takes 3d8 nonmagical bludgeoning damage, and it must succeed on a Strength Saving Throw or fall prone.',
        'level': '5',
        'casting_time': '1 action',
        'range': '300 feet',
        'components': 'V, S',
        'duration': 'Concentration, up to 1 minute',
        'school': 'Evocation',
        'concentration': True,

    }
}