cr_1_monsters = {
    "Animated Armor": {
        "hit_points": "33 (6d8 + 6)",
        "armor_class": 18,
        "speed": "25 ft.",
        "size": "Medium",
        "type": "Construct",
        "alignment": "Unaligned",
        "senses": "Blindsight 60 ft. (blind beyond this radius), Passive Perception 10",
        "damage_immunities": "Poison, Psychic",
        "condition_immunities": "Blinded, Charmed, Deafened, Exhaustion, Frightened, Poisoned",
        "challenge": "1",
        "actions": {
            "Multiattack": "The animated armor makes two melee attacks.",
            "Slam": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage.",
        },
    },
    "Brass Dragon Wyrmling": {
        "hit_points": "16 (3d8 + 3)",
        "armor_class": 16,
        "speed": "30 ft., burrow 15 ft., fly 60 ft.",
        "size": "Medium",
        "type": "Dragon",
        "subtype": "Brass",
        "alignment": "Chaotic Good",
        "senses": "Blindsight 10 ft., Darkvision 60 ft., Passive Perception 10",
        "languages": "Draconic",
        "ability_scores": {
            "strength": 13,
            "dexterity": 10,
            "constitution": 13,
            "intelligence": 10,
            "wisdom": 11,
            "charisma": 13,
        },
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
            "Breath Weapon (Recharge 5-6)": "The dragon exhales a line of fire in a 20-foot line that is 5 feet wide. Each creature in that line must make a DC 11 Dexterity saving throw, taking 14 (4d6) fire damage on a failed save, or half as much damage on a successful one.",
        },
        "special_abilities": {
            "Fire Breath": "The dragon can use its action to exhale fire in a 15-foot cone. Each creature in that area must make a DC 11 Dexterity saving throw, taking 14 (4d6) fire damage on a failed save, or half as much damage on a successful one.",
            "Sleep Breath (Recharge 5-6)": "The dragon exhales sleep gas in a 15-foot cone. Each creature in that area must succeed on a DC 11 Constitution saving throw or fall unconscious for 5 minutes. This effect ends for a creature if it takes damage or someone uses an action to wake it.",
        },
    },
    "Brown Bear": {
        "hit_points": "34 (4d10 + 12)",
        "armor_class": 11,
        "speed": "40 ft., climb 30 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Multiattack": "The bear makes two attacks: one with its bite and one with its claws.",
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.",
            "Claws": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.",
        },
    },
    "Bugbear": {
        "hit_points": "27 (5d8 + 5)",
        "armor_class": 16,
        "speed": "30 ft.",
        "size": "Medium",
        "type": "Humanoid",
        "subtype": "Goblinoid",
        "alignment": "Chaotic Evil",
        "senses": "Darkvision 60 ft., Passive Perception 9",
        "languages": "Common, Goblin",
        "ability_scores": {
            "strength": 15,
            "dexterity": 14,
            "constitution": 13,
            "intelligence": 8,
            "wisdom": 11,
            "charisma": 9,
        },
        "challenge": "1",
        "actions": {
            "Morningstar": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage.",
            "Javelin": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range.",
        },
        "special_abilities": {
            "Brute": "A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).",
            "Surprise Attack": "If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack.",
        },
    },
    "Copper Dragon Wyrmling": {
        "hit_points": "22 (4d8 + 4)",
        "armor_class": 16,
        "speed": "30 ft., climb 30 ft., fly 60 ft.",
        "size": "Medium",
        "type": "Dragon",
        "subtype": "Copper",
        "alignment": "Chaotic Good",
        "senses": "Blindsight 10 ft., Darkvision 60 ft., Passive Perception 10",
        "languages": "Draconic",
        "ability_scores": {
            "strength": 15,
            "dexterity": 12,
            "constitution": 13,
            "intelligence": 12,
            "wisdom": 11,
            "charisma": 14,
        },
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage.",
            "Breath Weapons (Recharge 5-6)": "The dragon uses one of the following breath weapons.",
            "Acid Breath": "The dragon exhales acid in a 30-foot line that is 5 feet wide. Each creature in that line must make a DC 11 Dexterity saving throw, taking 22 (4d10) acid damage on a failed save, or half as much damage on a successful one.",
            "Slowing Breath": "The dragon exhales gas in a 15-foot cone. Each creature in that area must succeed on a DC 11 Dexterity saving throw or have its speed halved for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
        },
        "special_abilities": {
            "Damage Immunities": "Acid",
            "False Appearance": "While the dragon remains motionless, it is indistinguishable from a copper statue.",
        },
    },
    "Death Dog": {
        "hit_points": "39 (6d8 + 12)",
        "armor_class": 12,
        "speed": "40 ft.",
        "size": "Medium",
        "type": "Monstrosity",
        "alignment": "Neutral Evil",
        "senses": "Darkvision 120 ft., Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage plus 4 (1d8) necrotic damage.",
        },
        "special_abilities": {
            "Two-Headed": "The dog has advantage on Wisdom (Perception) checks and on saving throws against being blinded, charmed, deafened, frightened, stunned, or knocked unconscious.",
            "Baying Howl (Recharge 5-6)": "Each creature of the dog's choice within 120 feet of it that can hear its howl and that isn't a death dog must succeed on a DC 12 Wisdom saving throw or be frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
        },
    },
    "Dire Wolf": {
        "hit_points": "37 (5d10 + 10)",
        "armor_class": 14,
        "speed": "50 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
        },
    },
    "Dryad": {
        "hit_points": "22 (5d8)",
        "armor_class": 11,
        "speed": "30 ft.",
        "size": "Medium",
        "type": "Fey",
        "alignment": "Neutral Good",
        "senses": "Darkvision 60 ft., Passive Perception 11",
        "languages": "Elvish, Sylvan",
        "ability_scores": {
            "strength": 10,
            "dexterity": 12,
            "constitution": 11,
            "intelligence": 14,
            "wisdom": 15,
            "charisma": 18,
        },
        "challenge": "1",
        "actions": {
            "Club": "Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.",
        },
        "special_abilities": {
            "Fey Charm": "The dryad targets one humanoid or beast that she can see within 30 feet of her. If the target can see the dryad, it must succeed on a DC 14 Wisdom saving throw or be magically charmed. The charmed creature regards the dryad as a trusted friend to be heeded and protected. Although the target isn't under the dryad's control, it takes the dryad's requests or actions in the most favorable way it can, and it is a willing target for the dryad's Fey Charm action. Each time the dryad or its allies do anything harmful to the target, it can repeat the saving throw, ending the effect on itself on a success. Otherwise, the effect lasts 24 hours or until the dryad dies, is on a different plane of existence from the target, or ends the effect as a bonus action. If a target's saving throw is successful, the target is immune to the dryad's Fey Charm for the next 24 hours.",
            "Innate Spellcasting": "The dryad's innate spellcasting ability is Charisma (spell save DC 14). She can innately cast the following spells, requiring no material components:",
            "At will": "druidcraft",
            "3/day each": "entangle, goodberry",
            "1/day each": "barkskin, pass without trace, shillelagh",
        },
    },
    "Duergar": {
        "hit_points": "26 (4d8 + 8)",
        "armor_class": 16,
        "speed": "25 ft.",
        "size": "Medium",
        "type": "Humanoid",
        "subtype": "Dwarf",
        "alignment": "Lawful Evil",
        "senses": "Darkvision 120 ft., Passive Perception 9",
        "languages": "Dwarvish, Undercommon",
        "ability_scores": {
            "strength": 14,
            "dexterity": 11,
            "constitution": 14,
            "intelligence": 11,
            "wisdom": 10,
            "charisma": 9,
        },
        "challenge": "1",
        "actions": {
            "War Pick": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage, or 11 (2d8 + 2) piercing damage if used with two hands to make a melee attack.",
            "Javelin": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage, or 8 (2d6 + 2) piercing damage if used with two hands to make a melee attack.",
        },
        "special_abilities": {
            "Duergar Resilience": "The duergar has advantage on saving throws against poison, spells, and illusions, as well as to resist being charmed or paralyzed.",
            "Enlarge (Recharges after a Short or Long Rest)": "For 1 minute, the duergar magically increases in size, along with anything it is wearing or carrying. While enlarged, the duergar is Large, doubles its damage dice on Strength-based weapon attacks (included in the attacks), and makes Strength checks and saving throws with advantage. If the duergar lacks the room to become Large, it attains the maximum size possible in the space available.",
        },
    },
    "Ghoul": {
        "hit_points": "22 (5d8)",
        "armor_class": 12,
        "speed": "30 ft.",
        "size": "Medium",
        "type": "Undead",
        "alignment": "Chaotic Evil",
        "senses": "Darkvision 60 ft., Passive Perception 10",
        "languages": "Understands the languages it knew in life but can't speak",
        "ability_scores": {
            "strength": 13,
            "dexterity": 15,
            "constitution": 10,
            "intelligence": 7,
            "wisdom": 10,
            "charisma": 6,
        },
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) piercing damage.",
        },
        "special_abilities": {
            "Bite": "If the target is a creature other than an undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
            "Claw (1/Turn)": "The ghoul makes two attacks with its claws.",
            "Claw": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 8 (2d4 + 3) slashing damage. If the target is a creature other than an undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
        },
    },
    "Giant Eagle": {
        "hit_points": "26 (4d10 + 4)",
        "armor_class": 13,
        "speed": "10 ft., fly 80 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Neutral Good",
        "senses": "Passive Perception 16",
        "languages": "Understands Common and Auran but can't speak",
        "ability_scores": {
            "strength": 16,
            "dexterity": 17,
            "constitution": 13,
            "intelligence": 8,
            "wisdom": 14,
            "charisma": 10,
        },
        "challenge": "1",
        "actions": {
            "Multiattack": "The eagle makes two attacks: one with its beak and one with its talons.",
            "Beak": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.",
            "Talons": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.",
        },
        "special_abilities": {
            "Keen Sight": "The eagle has advantage on Wisdom (Perception) checks that rely on sight.",
        },
    },
    "Giant Hyena": {
        "hit_points": "45 (6d10 + 12)",
        "armor_class": 12,
        "speed": "50 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage.",
        },
        "special_abilities": {
            "Rampage": "When the hyena reduces a creature to 0 hit points with a melee attack on its turn, the hyena can take a bonus action to move up to half its speed and make a bite attack.",
        },
    },
    "Giant Octopus": {
        "hit_points": "52 (8d10 + 8)",
        "armor_class": 11,
        "speed": "10 ft., swim 60 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Darkvision 60 ft., Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Tentacles": "Melee Weapon Attack: +5 to hit, reach 15 ft., one target. Hit: 10 (2d6 + 3) bludgeoning damage. If the target is a creature, it is grappled (escape DC 16). Until this grapple ends, the octopus can't use its tentacles on another target.",
            "Ink Cloud (Recharges after a Short or Long Rest)": "A 20-foot-radius cloud of ink extends all around the octopus if it is underwater. The area is heavily obscured for 1 minute, although a significant current can disperse the ink. After releasing the ink, the octopus can use the Dash action as a bonus action.",
        },
    },
    "Giant Spider": {
        "hit_points": "26 (4d10 + 4)",
        "armor_class": 14,
        "speed": "30 ft., climb 30 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Darkvision 60 ft., Passive Perception 10",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much damage on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.",
            "Web (Recharge 5-6)": "The spider shoots a web at a creature it can see within 30 feet of it. The target must succeed on a DC 12 Dexterity saving throw or be restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success. The webbing can also be attacked and destroyed (AC 10; hp 5; vulnerability to fire damage; immunity to bludgeoning, poison, and psychic damage).",
        },
    },
    "Giant Toad": {
        "hit_points": "39 (6d10 + 6)",
        "armor_class": 11,
        "speed": "20 ft., swim 40 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Darkvision 30 ft., Passive Perception 10",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage plus 5 (1d10) poison damage, and the target is grappled (escape DC 13). Until this grapple ends, the target is restrained, and the toad can't bite another target.",
            "Swallow": "The toad makes one bite attack against a Medium or smaller target it is grappling. If the attack hits, the target is swallowed, and the grapple ends. The swallowed target is blinded and restrained, it has total cover against attacks and other effects outside the toad, and it takes 10 (3d6) acid damage at the start of each of the toad's turns. The toad can have only one target swallowed at a time. If the toad dies, a swallowed creature is no longer restrained by it and can escape from the corpse using 5 feet of movement, exiting prone.",
        },
    },
    "Giant Vulture": {
        "hit_points": "22 (4d8 + 4)",
        "armor_class": 10,
        "speed": "10 ft., fly 60 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Neutral Evil",
        "senses": "Passive Perception 11",
        "languages": "Understands Common but can't speak",
        "ability_scores": {
            "strength": 15,
            "dexterity": 10,
            "constitution": 12,
            "intelligence": 6,
            "wisdom": 12,
            "charisma": 7,
        },
        "challenge": "1",
        "actions": {
            "Multiattack": "The vulture makes two attacks: one with its beak and one with its talons.",
            "Beak": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage.",
            "Talons": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 9 (2d6 + 2) slashing damage.",
        },
        "special_abilities": {
            "Keen Sight and Smell": "The vulture has advantage on Wisdom (Perception) checks that rely on sight or smell.",
        },
    },
    "Harpy": {
        "hit_points": "38 (7d8 + 7)",
        "armor_class": 11,
        "speed": "20 ft., fly 40 ft.",
        "size": "Medium",
        "type": "Monstrosity",
        "subtype": "Shapechanger",
        "alignment": "Chaotic Evil",
        "senses": "Passive Perception 12",
        "languages": "Common",
        "ability_scores": {
            "strength": 12,
            "dexterity": 13,
            "constitution": 12,
            "intelligence": 7,
            "wisdom": 10,
            "charisma": 13,
        },
        "challenge": "1",
        "actions": {
            "Multiattack": "The harpy makes two attacks: one with its claws and one with its club.",
            "Claws": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4 + 1) slashing damage.",
            "Club": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4 + 1) bludgeoning damage.",
            "Luring Song (Recharge 5-6)": "The harpy sings a magical melody. Every humanoid and giant within 300 feet of the harpy that can hear the song must succeed on a DC 11 Wisdom saving throw or be charmed until the song ends. The harpy must take a bonus action on its subsequent turns to continue singing. It can stop singing at any time. The song ends if the harpy is incapacitated.",
        },
    },
    "Hippogriff": {
        "hit_points": "19 (3d10 + 3)",
        "armor_class": 11,
        "speed": "40 ft., fly 60 ft.",
        "size": "Large",
        "type": "Monstrosity",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "languages": "understands Common, but can't speak",
        "ability_scores": {
            "strength": 17,
            "dexterity": 13,
            "constitution": 13,
            "intelligence": 2,
            "wisdom": 12,
            "charisma": 8,
        },
        "challenge": "1",
        "actions": {
            "Beak": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage.",
            "Claws": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.",
        },
        "special_abilities": {
            "Keen Sight": "The hippogriff has advantage on Wisdom (Perception) checks that rely on sight.",
        },
    },
    "Imp": {
        "hit_points": "10 (3d4 + 3)",
        "armor_class": 13,
        "speed": "20 ft., fly 40 ft.",
        "size": "Tiny",
        "type": "Fiend",
        "alignment": "Lawful Evil",
        "senses": "Devil's Sight, Passive Perception 10",
        "languages": "Infernal, Common",
        "ability_scores": {
            "strength": 6,
            "dexterity": 17,
            "constitution": 13,
            "intelligence": 11,
            "wisdom": 12,
            "charisma": 14,
        },
        "challenge": "1",
        "actions": {
            "Sting": "Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 5 (1d4 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.",
            "Invisibility": "The imp magically turns invisible until it attacks or until its concentration ends (as if concentrating on a spell). Any equipment the imp wears or carries is invisible with it.",
            "Shapechanger": "The imp can use its action to polymorph into a beast form that resembles a rat (speed 20 ft.), a raven (20 ft., fly 60 ft.), or a spider (20 ft., climb 20 ft.), or back into its true form. Its statistics are the same in each form, except for the speed changes noted. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.",
            "Variant: Familiar": "The imp can serve another creature as a familiar, forming a telepathic bond with its willing master. While the two are bonded, the master can sense what the imp senses as long as they are within 1 mile of each other. While the imp is within 10 feet of its master, the master shares the imp's Magic Resistance trait. If its master violates the terms of the contract, the imp can end its service as a familiar, ending the telepathic bond.",
        },
        "special_abilities": {
            "Devil's Sight": "Magical darkness doesn't impede the imp's darkvision.",
            "Magic Resistance": "The imp has advantage on saving throws against spells and other magical effects.",
        },
    },
    "Lion": {
        "hit_points": "26 (4d8 + 8)",
        "armor_class": 12,
        "speed": "50 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Multiattack": "The lion makes two attacks: one with its bite and one with its claws.",
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage.",
            "Claws": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.",
        },
        "special_abilities": {
            "Keen Smell": "The lion has advantage on Wisdom (Perception) checks that rely on smell.",
            "Pack Tactics": "The lion has advantage on an attack roll against a creature if at least one of the lion's allies is within 5 feet of the creature and the ally isn't incapacitated.",
        },
    },
    "Quasit": {
        "hit_points": "7 (3d4)",
        "armor_class": 13,
        "speed": "40 ft., fly 40 ft.",
        "size": "Tiny",
        "type": "Fiend (Demon)",
        "alignment": "Chaotic Evil",
        "senses": "Darkvision 120 ft., Passive Perception 10",
        "languages": "Abyssal, Common",
        "ability_scores": {
            "strength": 5,
            "dexterity": 17,
            "constitution": 10,
            "intelligence": 7,
            "wisdom": 10,
            "charisma": 10,
        },
        "challenge": "1",
        "actions": {
            "Claws (Bite in Beast Form)": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d4 + 3) slashing damage.",
            "Scare (1/Day)": "The quasit magically emits screeching sounds. Each creature of the quasit's choice within 20 feet of it that can hear the sounds must succeed on a DC 10 Wisdom saving throw or become frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
            "Invisibility": "The quasit magically turns invisible until it attacks or until its concentration ends (as if concentrating on a spell). Any equipment the quasit wears or carries is invisible with it.",
            "Variant: Familiar": "The quasit can serve another creature as a familiar, forming a telepathic bond with its willing master. While the two are bonded, the master can sense what the quasit senses as long as they are within 1 mile of each other. While the quasit is within 10 feet of its master, the master shares the quasit's Magic Resistance trait. If its master violates the terms of the contract, the quasit can end its service as a familiar, ending the telepathic bond.",
        },
        "special_abilities": {
            "Magic Resistance": "The quasit has advantage on saving throws against spells and other magical effects.",
        },
    },
    "Specter": {
        "hit_points": "22 (5d8)",
        "armor_class": 12,
        "speed": "0 ft., fly 50 ft. (hover)",
        "size": "Medium",
        "type": "Undead",
        "alignment": "Chaotic Evil",
        "senses": "Darkvision 60 ft., Passive Perception 10",
        "languages": "Understands all languages it knew in life but can't speak",
        "ability_scores": {
            "strength": 1,
            "dexterity": 14,
            "constitution": 11,
            "intelligence": 10,
            "wisdom": 10,
            "charisma": 11,
        },
        "challenge": "1",
        "actions": {
            "Life Drain": "Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) necrotic damage. The target must succeed on a DC 10 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.",
            "Incorporeal Movement": "The specter can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.",
        },
        "special_abilities": {
            "Sunlight Sensitivity": "While in sunlight, the specter has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.",
        },
    },
    "Spy": {
        "hit_points": "27 (6d8)",
        "armor_class": 12,
        "speed": "30 ft.",
        "size": "Medium",
        "type": "Humanoid",
        "subtype": "Any race (usually Human)",
        "alignment": "Any Alignment",
        "senses": "Passive Perception 12",
        "languages": "Any four languages",
        "ability_scores": {
            "strength": 10,
            "dexterity": 15,
            "constitution": 10,
            "intelligence": 12,
            "wisdom": 14,
            "charisma": 16,
        },
        "challenge": "1",
        "actions": {
            "Multiattack": "The spy makes two melee attacks.",
            "Shortsword": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
            "Hand Crossbow": "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
            "Poisoned Dagger": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one creature. Hit: 5 (1d4 + 2) piercing damage, and the target must make a DC 13 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.",
        },
        "special_abilities": {
            "Evasion": "If the spy is subjected to an effect that allows it to make a Dexterity saving throw to take only half damage, the spy instead takes no damage if it succeeds on the saving throw, and only half damage if it fails.",
            "Sneak Attack (1/Turn)": "The spy deals an extra 7 (2d6) damage when it hits a target with a weapon attack and has advantage on the attack roll, or when the target is within 5 feet of an ally of the spy that isn't incapacitated and the spy doesn't have disadvantage on the attack roll.",
        },
    },
    "Swarm of Quippers": {
        "hit_points": "28 (8d8)",
        "armor_class": 13,
        "speed": "0 ft., swim 40 ft.",
        "size": "Medium",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Darkvision 60 ft., Passive Perception 10",
        "challenge": "1",
        "actions": {
            "Bite": "Melee Weapon Attack: +5 to hit, reach 0 ft., one creature in the swarm's space. Hit: 14 (4d6) piercing damage, or 7 (2d6) piercing damage if the swarm has half of its hit points or fewer.",
            "Blood Frenzy": "The swarm has advantage on melee attack rolls against any creature that doesn't have all its hit points.",
            "Water Breathing": "The swarm can breathe only underwater.",
        },
        "special_abilities": {
            "Keen Smell": "The swarm has advantage on Wisdom (Perception) checks that rely on smell.",
            "Swarm": "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny quipper. The swarm can't regain hit points or gain temporary hit points.",
        },
    },
    "Tiger": {
        "hit_points": "37 (5d10 + 10)",
        "armor_class": 12,
        "speed": "40 ft.",
        "size": "Large",
        "type": "Beast",
        "alignment": "Unaligned",
        "senses": "Passive Perception 13",
        "challenge": "1",
        "actions": {
            "Multiattack": "The tiger makes two attacks: one with its bite and one with its claws.",
            "Bite": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage.",
            "Claws": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d8 + 5) slashing damage.",
        },
        "special_abilities": {
            "Keen Smell": "The tiger has advantage on Wisdom (Perception) checks that rely on smell.",
            "Pounce": "If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.",
        },
    }
}
